import type { AnimationPreset } from './motion-types';

export const MOTION_PRESETS: AnimationPreset[] = [
  // ── Entrance ──────────────────────────────────────────────────────────
  {
    name: 'fadeIn',
    category: 'entrance',
    label: 'Fade In',
    icon: 'Eye',
    keyframes: [
      { time: 0, opacity: 0 },
      { time: 100, opacity: 1 },
    ],
    duration: 500,
    easing: 'easeOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'slideUp',
    category: 'entrance',
    label: 'Slide Up',
    icon: 'ArrowUp',
    keyframes: [
      { time: 0, opacity: 0, y: 40 },
      { time: 100, opacity: 1, y: 0 },
    ],
    duration: 600,
    easing: 'easeOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'slideDown',
    category: 'entrance',
    label: 'Slide Down',
    icon: 'ArrowDown',
    keyframes: [
      { time: 0, opacity: 0, y: -40 },
      { time: 100, opacity: 1, y: 0 },
    ],
    duration: 600,
    easing: 'easeOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'slideLeft',
    category: 'entrance',
    label: 'Slide Left',
    icon: 'ArrowLeft',
    keyframes: [
      { time: 0, opacity: 0, x: 60 },
      { time: 100, opacity: 1, x: 0 },
    ],
    duration: 600,
    easing: 'easeOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'slideRight',
    category: 'entrance',
    label: 'Slide Right',
    icon: 'ArrowRight',
    keyframes: [
      { time: 0, opacity: 0, x: -60 },
      { time: 100, opacity: 1, x: 0 },
    ],
    duration: 600,
    easing: 'easeOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'scaleIn',
    category: 'entrance',
    label: 'Scale In',
    icon: 'Maximize2',
    keyframes: [
      { time: 0, opacity: 0, scale: 0.5 },
      { time: 100, opacity: 1, scale: 1 },
    ],
    duration: 500,
    easing: 'backOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'flipInX',
    category: 'entrance',
    label: 'Flip In X',
    icon: 'RotateCw',
    keyframes: [
      { time: 0, opacity: 0, rotation: -90, scale: 0.8 },
      { time: 100, opacity: 1, rotation: 0, scale: 1 },
    ],
    duration: 700,
    easing: 'easeOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'flipInY',
    category: 'entrance',
    label: 'Flip In Y',
    icon: 'RotateCcw',
    keyframes: [
      { time: 0, opacity: 0, skewX: -30, scale: 0.8 },
      { time: 100, opacity: 1, skewX: 0, scale: 1 },
    ],
    duration: 700,
    easing: 'easeOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },

  // ── Emphasis ──────────────────────────────────────────────────────────
  {
    name: 'pulse',
    category: 'emphasis',
    label: 'Pulse',
    icon: 'Heart',
    keyframes: [
      { time: 0, scale: 1 },
      { time: 50, scale: 1.05 },
      { time: 100, scale: 1 },
    ],
    duration: 800,
    easing: 'easeInOut',
    loop: true,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'bounce',
    category: 'emphasis',
    label: 'Bounce',
    icon: 'ChevronsUp',
    keyframes: [
      { time: 0, y: 0 },
      { time: 20, y: -30 },
      { time: 40, y: 0 },
      { time: 55, y: -15 },
      { time: 70, y: 0 },
      { time: 82, y: -5 },
      { time: 100, y: 0 },
    ],
    duration: 1000,
    easing: 'easeOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'shake',
    category: 'emphasis',
    label: 'Shake',
    icon: 'AlertTriangle',
    keyframes: [
      { time: 0, x: 0 },
      { time: 10, x: -10, rotation: -3 },
      { time: 20, x: 10, rotation: 3 },
      { time: 30, x: -10, rotation: -3 },
      { time: 40, x: 10, rotation: 3 },
      { time: 50, x: -5, rotation: -1 },
      { time: 60, x: 5, rotation: 1 },
      { time: 100, x: 0, rotation: 0 },
    ],
    duration: 600,
    easing: 'easeInOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'wobble',
    category: 'emphasis',
    label: 'Wobble',
    icon: 'Waves',
    keyframes: [
      { time: 0, rotation: 0 },
      { time: 15, rotation: -5 },
      { time: 30, rotation: 3 },
      { time: 45, rotation: -3 },
      { time: 60, rotation: 2 },
      { time: 75, rotation: -1 },
      { time: 100, rotation: 0 },
    ],
    duration: 800,
    easing: 'easeInOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'tada',
    category: 'emphasis',
    label: 'Tada',
    icon: 'PartyPopper',
    keyframes: [
      { time: 0, scale: 1, rotation: 0 },
      { time: 10, scale: 0.9, rotation: -3 },
      { time: 20, scale: 0.9, rotation: -3 },
      { time: 30, scale: 1.1, rotation: 3 },
      { time: 40, scale: 1.1, rotation: -3 },
      { time: 50, scale: 1.1, rotation: 3 },
      { time: 60, scale: 1, rotation: 0 },
      { time: 100, scale: 1, rotation: 0 },
    ],
    duration: 1000,
    easing: 'easeInOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'jello',
    category: 'emphasis',
    label: 'Jello',
    icon: 'Pudding',
    keyframes: [
      { time: 0, skewX: 0, skewY: 0 },
      { time: 11, skewX: 5, skewY: 0 },
      { time: 22, skewX: -5, skewY: 0 },
      { time: 33, skewX: 3, skewY: -3 },
      { time: 44, skewX: -3, skewY: 3 },
      { time: 55, skewX: 2, skewY: -2 },
      { time: 66, skewX: -1, skewY: 1 },
      { time: 100, skewX: 0, skewY: 0 },
    ],
    duration: 900,
    easing: 'easeInOut',
    loop: false,
    delay: 0,
    direction: 'normal',
  },

  // ── Exit ──────────────────────────────────────────────────────────────
  {
    name: 'fadeOut',
    category: 'exit',
    label: 'Fade Out',
    icon: 'EyeOff',
    keyframes: [
      { time: 0, opacity: 1 },
      { time: 100, opacity: 0 },
    ],
    duration: 400,
    easing: 'easeIn',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'slideOutUp',
    category: 'exit',
    label: 'Slide Out Up',
    icon: 'ArrowUpFromLine',
    keyframes: [
      { time: 0, opacity: 1, y: 0 },
      { time: 100, opacity: 0, y: -60 },
    ],
    duration: 500,
    easing: 'easeIn',
    loop: false,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'scaleOut',
    category: 'exit',
    label: 'Scale Out',
    icon: 'Minimize2',
    keyframes: [
      { time: 0, opacity: 1, scale: 1 },
      { time: 100, opacity: 0, scale: 0.3 },
    ],
    duration: 400,
    easing: 'easeIn',
    loop: false,
    delay: 0,
    direction: 'normal',
  },

  // ── Loop ──────────────────────────────────────────────────────────────
  {
    name: 'float',
    category: 'loop',
    label: 'Float',
    icon: 'Cloud',
    keyframes: [
      { time: 0, y: 0 },
      { time: 50, y: -12 },
      { time: 100, y: 0 },
    ],
    duration: 3000,
    easing: 'easeInOut',
    loop: true,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'spin',
    category: 'loop',
    label: 'Spin',
    icon: 'Loader',
    keyframes: [
      { time: 0, rotation: 0 },
      { time: 100, rotation: 360 },
    ],
    duration: 2000,
    easing: 'linear',
    loop: true,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'breathe',
    category: 'loop',
    label: 'Breathe',
    icon: 'Wind',
    keyframes: [
      { time: 0, scale: 1, opacity: 0.8 },
      { time: 50, scale: 1.04, opacity: 1 },
      { time: 100, scale: 1, opacity: 0.8 },
    ],
    duration: 4000,
    easing: 'easeInOut',
    loop: true,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'pulseGlow',
    category: 'loop',
    label: 'Pulse Glow',
    icon: 'Sun',
    keyframes: [
      { time: 0, boxShadow: '0 0 0px rgba(99,102,241,0)', scale: 1 },
      { time: 50, boxShadow: '0 0 20px rgba(99,102,241,0.5)', scale: 1.02 },
      { time: 100, boxShadow: '0 0 0px rgba(99,102,241,0)', scale: 1 },
    ],
    duration: 2000,
    easing: 'easeInOut',
    loop: true,
    delay: 0,
    direction: 'normal',
  },
  {
    name: 'pendulum',
    category: 'loop',
    label: 'Pendulum',
    icon: 'Clock',
    keyframes: [
      { time: 0, rotation: 0 },
      { time: 50, rotation: 15 },
      { time: 100, rotation: 0 },
    ],
    duration: 1500,
    easing: 'easeInOut',
    loop: true,
    delay: 0,
    direction: 'alternate',
  },
];

export function getPresetByName(name: string): AnimationPreset | undefined {
  return MOTION_PRESETS.find((p) => p.name === name);
}

export function getPresetsByCategory(category: AnimationPreset['category']): AnimationPreset[] {
  return MOTION_PRESETS.filter((p) => p.category === category);
}

export const PRESET_CATEGORIES: { key: AnimationPreset['category']; label: string }[] = [
  { key: 'entrance', label: 'Entrance' },
  { key: 'emphasis', label: 'Emphasis' },
  { key: 'exit', label: 'Exit' },
  { key: 'loop', label: 'Loop' },
];