export interface DesignPlugin {
  id: string
  name: string
  description: string
  category: 'shapes' | 'charts' | 'icons' | 'layout' | 'wireframe' | 'diagrams' | 'text' | 'images' | 'colors' | 'export' | 'templates' | 'ai-tools' | 'collaboration' | 'accessibility' | 'math'
  icon: string // lucide icon name
  isInstalled: boolean
  isPopular?: boolean
  tags: string[]
  version: string
  author: string
}

export const DESIGN_PLUGINS: DesignPlugin[] = [
  // ── Shapes (7) ──────────────────────────────────────────────
  {
    id: 'shapes-basic',
    name: 'Basic Shapes',
    description: 'Rectangles, circles, triangles, and other foundational geometric primitives.',
    category: 'shapes',
    icon: 'Box',
    isInstalled: true,
    isPopular: true,
    tags: ['rectangle', 'circle', 'triangle', 'geometry', 'fundamentals'],
    version: '2.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'shapes-polygons',
    name: 'Polygons',
    description: 'Regular polygons with configurable sides from triangles to dodecagons.',
    category: 'shapes',
    icon: 'Pentagon',
    isInstalled: true,
    tags: ['pentagon', 'octagon', 'heptagon', 'polygon', 'sides'],
    version: '1.4.0',
    author: 'OpenCanvas',
  },
  {
    id: 'shapes-stars',
    name: 'Stars & Bursts',
    description: 'Star shapes and radial burst effects for badges and highlights.',
    category: 'shapes',
    icon: 'Star',
    isInstalled: true,
    isPopular: true,
    tags: ['star', 'burst', 'badge', 'highlight', 'radial'],
    version: '1.3.0',
    author: 'OpenCanvas',
  },
  {
    id: 'shapes-arrows',
    name: 'Arrows & Connectors',
    description: 'Directional arrows, chevrons, and connector lines with custom endpoints.',
    category: 'shapes',
    icon: 'ArrowRight',
    isInstalled: true,
    tags: ['arrow', 'connector', 'direction', 'chevron', 'flow'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'shapes-speech-bubbles',
    name: 'Speech Bubbles',
    description: 'Chat and thought bubbles for dialogue and annotation on the canvas.',
    category: 'shapes',
    icon: 'MessageSquare',
    isInstalled: true,
    tags: ['bubble', 'chat', 'dialogue', 'annotation', 'speech'],
    version: '1.2.0',
    author: 'OpenCanvas',
  },
  {
    id: 'shapes-hexagons',
    name: 'Hexagons',
    description: 'Honeycomb-style hexagons perfect for diagrams and infographics.',
    category: 'shapes',
    icon: 'Hexagon',
    isInstalled: true,
    tags: ['hexagon', 'honeycomb', 'infographic', 'tessellation'],
    version: '1.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'shapes-badges',
    name: 'Badges & Ribbons',
    description: 'Decorative badge and ribbon shapes for labels and awards.',
    category: 'shapes',
    icon: 'Badge',
    isInstalled: true,
    tags: ['badge', 'ribbon', 'label', 'award', 'decorative'],
    version: '1.0.0',
    author: 'ShapeLab',
  },

  // ── Charts (7) ──────────────────────────────────────────────
  {
    id: 'charts-bar',
    name: 'Bar Chart',
    description: 'Vertical and horizontal bar charts for comparing discrete categories.',
    category: 'charts',
    icon: 'BarChart3',
    isInstalled: true,
    isPopular: true,
    tags: ['bar', 'chart', 'comparison', 'data', 'visualization'],
    version: '3.2.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'charts-line',
    name: 'Line Chart',
    description: 'Trend lines and multi-series area fills for time-series data.',
    category: 'charts',
    icon: 'LineChart',
    isInstalled: true,
    isPopular: true,
    tags: ['line', 'trend', 'time-series', 'area', 'graph'],
    version: '3.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'charts-pie',
    name: 'Pie & Donut Chart',
    description: 'Proportional slices showing part-to-whole relationships.',
    category: 'charts',
    icon: 'PieChart',
    isInstalled: true,
    tags: ['pie', 'donut', 'proportion', 'percentage', 'slice'],
    version: '2.4.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'charts-area',
    name: 'Area Chart',
    description: 'Stacked and layered area charts emphasizing volume over time.',
    category: 'charts',
    icon: 'Layers',
    isInstalled: true,
    tags: ['area', 'stacked', 'volume', 'filled', 'cumulative'],
    version: '1.5.0',
    author: 'ChartKit',
  },
  {
    id: 'charts-scatter',
    name: 'Scatter Plot',
    description: 'X-Y scatter plots revealing correlations and distribution clusters.',
    category: 'charts',
    icon: 'Target',
    isInstalled: true,
    tags: ['scatter', 'correlation', 'distribution', 'dot', 'xy'],
    version: '1.3.0',
    author: 'ChartKit',
  },
  {
    id: 'charts-radar',
    name: 'Radar Chart',
    description: 'Multi-axis radar/spider charts for comparing multiple metrics.',
    category: 'charts',
    icon: 'Compass',
    isInstalled: true,
    tags: ['radar', 'spider', 'multi-axis', 'comparison', 'polygon'],
    version: '1.2.0',
    author: 'ChartKit',
  },
  {
    id: 'charts-treemap',
    name: 'Treemap',
    description: 'Hierarchical nested rectangles sized by value for part-of-whole views.',
    category: 'charts',
    icon: 'Layout',
    isInstalled: true,
    tags: ['treemap', 'hierarchy', 'nested', 'proportion', 'rectangle'],
    version: '1.0.0',
    author: 'DataViz Lab',
  },

  // ── Icons (7) ───────────────────────────────────────────────
  {
    id: 'icons-lucide',
    name: 'Lucide Icons',
    description: 'Beautiful, consistent open-source icon set with 1,500+ icons.',
    category: 'icons',
    icon: 'Star',
    isInstalled: true,
    isPopular: true,
    tags: ['lucide', 'open-source', 'svg', 'icon-set', 'vector'],
    version: '0.460.0',
    author: 'Lucide Contributors',
  },
  {
    id: 'icons-font-awesome',
    name: 'Font Awesome',
    description: 'The web\'s most popular icon library with 2,000+ icons.',
    category: 'icons',
    icon: 'Heart',
    isInstalled: true,
    isPopular: true,
    tags: ['font-awesome', 'brands', 'solid', 'regular', 'classic'],
    version: '6.5.0',
    author: 'Font Awesome Team',
  },
  {
    id: 'icons-material',
    name: 'Material Design Icons',
    description: 'Google\'s Material icon set covering common UI actions and objects.',
    category: 'icons',
    icon: 'Globe',
    isInstalled: true,
    isPopular: true,
    tags: ['material', 'google', 'android', 'ui', 'design-system'],
    version: '7.4.0',
    author: 'Google Material',
  },
  {
    id: 'icons-heroicons',
    name: 'Heroicons',
    description: 'Crafted by the Tailwind Labs team, optimized for modern interfaces.',
    category: 'icons',
    icon: 'Sparkles',
    isInstalled: true,
    tags: ['heroicons', 'tailwind', 'outline', 'solid', 'modern'],
    version: '2.1.0',
    author: 'Tailwind Labs',
  },
  {
    id: 'icons-tabler',
    name: 'Tabler Icons',
    description: 'Over 5,000 pixel-perfect SVG icons with consistent styling.',
    category: 'icons',
    icon: 'Grid3X3',
    isInstalled: true,
    tags: ['tabler', 'svg', 'pixel-perfect', 'comprehensive', 'icons'],
    version: '3.6.0',
    author: 'Tabler',
  },
  {
    id: 'icons-phosphor',
    name: 'Phosphor Icons',
    description: 'Flexible icon family with six weights from thin to bold.',
    category: 'icons',
    icon: 'MousePointer',
    isInstalled: true,
    tags: ['phosphor', 'weights', 'flexible', 'family', 'variable'],
    version: '2.1.0',
    author: 'Phosphor Icons',
  },
  {
    id: 'icons-remix',
    name: 'Remix Icon',
    description: 'Neutral, system-symbolic icon set with 2,800+ icons.',
    category: 'icons',
    icon: 'RefreshCw',
    isInstalled: true,
    tags: ['remix', 'neutral', 'symbolic', 'line', 'fill'],
    version: '4.2.0',
    author: 'Remix Design',
  },

  // ── Layout (6) ──────────────────────────────────────────────
  {
    id: 'layout-grid',
    name: 'Grid System',
    description: '12-column and auto-fit grid overlays for precise element alignment.',
    category: 'layout',
    icon: 'Grid3X3',
    isInstalled: true,
    tags: ['grid', 'columns', 'alignment', 'overlay', 'structure'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'layout-flexbox',
    name: 'Flexbox Layout',
    description: 'Visual flexbox direction and distribution controls on the canvas.',
    category: 'layout',
    icon: 'Columns3',
    isInstalled: true,
    tags: ['flexbox', 'flex', 'direction', 'distribution', 'spacing'],
    version: '1.3.0',
    author: 'LayoutKit',
  },
  {
    id: 'layout-masonry',
    name: 'Masonry Layout',
    description: 'Pinterest-style masonry grids with variable-height cards.',
    category: 'layout',
    icon: 'Layout',
    isInstalled: true,
    tags: ['masonry', 'pinterest', 'waterfall', 'cards', 'variable'],
    version: '1.1.0',
    author: 'LayoutKit',
  },
  {
    id: 'layout-css-grid',
    name: 'CSS Grid Builder',
    description: 'Drag-and-drop grid template builder with named areas.',
    category: 'layout',
    icon: 'Frame',
    isInstalled: true,
    tags: ['css-grid', 'template', 'areas', 'builder', 'visual'],
    version: '1.0.0',
    author: 'LayoutKit',
  },
  {
    id: 'layout-responsive',
    name: 'Responsive Breakpoints',
    description: 'Preview and switch between mobile, tablet, and desktop viewports.',
    category: 'layout',
    icon: 'Monitor',
    isInstalled: false,
    tags: ['responsive', 'breakpoint', 'viewport', 'mobile', 'desktop'],
    version: '1.2.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'layout-spacing',
    name: 'Spacing System',
    description: 'Consistent 4px-based spacing scale with visual spacing ruler.',
    category: 'layout',
    icon: 'Move',
    isInstalled: false,
    tags: ['spacing', 'padding', 'margin', 'scale', 'consistency'],
    version: '1.0.0',
    author: 'DesignTokens',
  },

  // ── Wireframe (7) ───────────────────────────────────────────
  {
    id: 'wireframe-inputs',
    name: 'Input Fields',
    description: 'Text inputs, textareas, selects, and checkboxes in wireframe style.',
    category: 'wireframe',
    icon: 'FormInput',
    isInstalled: false,
    tags: ['input', 'text-field', 'form', 'wireframe', 'skeleton'],
    version: '2.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'wireframe-buttons',
    name: 'Buttons',
    description: 'Primary, secondary, ghost, and icon button wireframe variants.',
    category: 'wireframe',
    icon: 'MousePointer',
    isInstalled: false,
    tags: ['button', 'cta', 'action', 'wireframe', 'interactive'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'wireframe-cards',
    name: 'Cards',
    description: 'Content cards with headers, bodies, images, and footer slots.',
    category: 'wireframe',
    icon: 'Layers',
    isInstalled: false,
    tags: ['card', 'content', 'container', 'wireframe', 'block'],
    version: '1.3.0',
    author: 'WireKit',
  },
  {
    id: 'wireframe-navbars',
    name: 'Navigation Bars',
    description: 'Top nav and breadcrumb bars with logo, links, and actions.',
    category: 'wireframe',
    icon: 'Navigation',
    isInstalled: false,
    tags: ['navbar', 'navigation', 'header', 'links', 'wireframe'],
    version: '1.2.0',
    author: 'WireKit',
  },
  {
    id: 'wireframe-forms',
    name: 'Form Builders',
    description: 'Complete form layouts with validation states and error messages.',
    category: 'wireframe',
    icon: 'Clipboard',
    isInstalled: false,
    tags: ['form', 'validation', 'error', 'submit', 'layout'],
    version: '1.1.0',
    author: 'WireKit',
  },
  {
    id: 'wireframe-tables',
    name: 'Data Tables',
    description: 'Sortable, paginated table wireframes with row actions.',
    category: 'wireframe',
    icon: 'Table',
    isInstalled: false,
    tags: ['table', 'data', 'sort', 'paginate', 'grid'],
    version: '1.0.0',
    author: 'WireKit',
  },
  {
    id: 'wireframe-modals',
    name: 'Modals & Dialogs',
    description: 'Overlay dialogs, drawers, and confirmation prompt wireframes.',
    category: 'wireframe',
    icon: 'Maximize2',
    isInstalled: false,
    tags: ['modal', 'dialog', 'drawer', 'overlay', 'prompt'],
    version: '1.2.0',
    author: 'WireKit',
  },

  // ── Diagrams (7) ────────────────────────────────────────────
  {
    id: 'diagrams-flowchart',
    name: 'Flowchart',
    description: 'Process flow diagrams with decision nodes and loopback arrows.',
    category: 'diagrams',
    icon: 'Workflow',
    isInstalled: false,
    isPopular: true,
    tags: ['flowchart', 'process', 'decision', 'flow', 'logic'],
    version: '3.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'diagrams-uml-class',
    name: 'UML Class Diagram',
    description: 'Class boxes with attributes, methods, and relationship lines.',
    category: 'diagrams',
    icon: 'Layers',
    isInstalled: false,
    tags: ['uml', 'class', 'inheritance', 'methods', 'attributes'],
    version: '2.2.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-er',
    name: 'ER Diagram',
    description: 'Entity-relationship diagrams with cardinality notations.',
    category: 'diagrams',
    icon: 'GitBranch',
    isInstalled: false,
    tags: ['er', 'entity', 'relationship', 'database', 'schema'],
    version: '2.0.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-mind-map',
    name: 'Mind Map',
    description: 'Radial mind mapping with auto-layout and collapsible branches.',
    category: 'diagrams',
    icon: 'Lightbulb',
    isInstalled: false,
    tags: ['mind-map', 'radial', 'brainstorm', 'branches', 'hierarchy'],
    version: '2.1.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-org-chart',
    name: 'Org Chart',
    description: 'Organizational hierarchy trees with roles and reporting lines.',
    category: 'diagrams',
    icon: 'Users',
    isInstalled: false,
    tags: ['org-chart', 'hierarchy', 'organization', 'reporting', 'team'],
    version: '1.4.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-sequence',
    name: 'Sequence Diagram',
    description: 'Interaction sequences between actors with lifelines and messages.',
    category: 'diagrams',
    icon: 'ArrowRight',
    isInstalled: false,
    tags: ['sequence', 'interaction', 'lifeline', 'message', 'uml'],
    version: '1.3.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-state',
    name: 'State Diagram',
    description: 'Finite state machines with transitions and guard conditions.',
    category: 'diagrams',
    icon: 'RotateCw',
    isInstalled: false,
    tags: ['state', 'machine', 'transition', 'guard', 'fsm'],
    version: '1.2.0',
    author: 'DiagramForge',
  },

  // ── Text (7) ────────────────────────────────────────────────
  {
    id: 'text-typography-scale',
    name: 'Typography Scale',
    description: 'Modular type scale with predefined size ratios and presets.',
    category: 'text',
    icon: 'Type',
    isInstalled: false,
    isPopular: true,
    tags: ['typography', 'scale', 'modular', 'ratio', 'sizes'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'text-headings',
    name: 'Heading Styles',
    description: 'H1 through H6 heading presets with weight and spacing.',
    category: 'text',
    icon: 'Heading',
    isInstalled: false,
    tags: ['heading', 'h1', 'h2', 'h3', 'title'],
    version: '1.5.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'text-body',
    name: 'Body Text',
    description: 'Paragraph and running text styles with optimal line height.',
    category: 'text',
    icon: 'FileText',
    isInstalled: false,
    tags: ['body', 'paragraph', 'readability', 'line-height', 'prose'],
    version: '1.3.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'text-caption',
    name: 'Captions & Overlines',
    description: 'Small text styles for captions, labels, and overlines.',
    category: 'text',
    icon: 'Minimize2',
    isInstalled: false,
    tags: ['caption', 'overline', 'small', 'label', 'subtle'],
    version: '1.1.0',
    author: 'TypeLab',
  },
  {
    id: 'text-blockquote',
    name: 'Blockquote',
    description: 'Styled blockquote elements with decorative borders and attribution.',
    category: 'text',
    icon: 'Quote',
    isInstalled: false,
    tags: ['blockquote', 'quote', 'attribution', 'emphasis', 'citation'],
    version: '1.0.0',
    author: 'TypeLab',
  },
  {
    id: 'text-code-block',
    name: 'Code Block',
    description: 'Syntax-highlighted code blocks with line numbers and copy button.',
    category: 'text',
    icon: 'Code',
    isInstalled: false,
    tags: ['code', 'syntax', 'programming', 'snippet', 'monospace'],
    version: '1.2.0',
    author: 'TypeLab',
  },
  {
    id: 'text-list-styles',
    name: 'List Styles',
    description: 'Bulleted, numbered, and custom marker list configurations.',
    category: 'text',
    icon: 'List',
    isInstalled: false,
    tags: ['list', 'bullet', 'numbered', 'marker', 'ordered'],
    version: '1.0.0',
    author: 'TypeLab',
  },

  // ── Images (7) ──────────────────────────────────────────────
  {
    id: 'images-placeholder',
    name: 'Image Placeholder',
    description: 'Configurable placeholder images with custom dimensions and labels.',
    category: 'images',
    icon: 'Image',
    isInstalled: false,
    isPopular: true,
    tags: ['placeholder', 'dummy', 'dimensions', 'lorem-pixel', 'skeleton'],
    version: '2.2.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'images-photo-grid',
    name: 'Photo Grid',
    description: 'Drag-to-resize photo grid with configurable gaps and cropping.',
    category: 'images',
    icon: 'Grid3X3',
    isInstalled: false,
    tags: ['photo-grid', 'gallery', 'crop', 'gap', 'images'],
    version: '1.4.0',
    author: 'MediaKit',
  },
  {
    id: 'images-gallery',
    name: 'Gallery',
    description: 'Scrollable image gallery with thumbnails and navigation.',
    category: 'images',
    icon: 'Layers',
    isInstalled: false,
    tags: ['gallery', 'thumbnail', 'scroll', 'browse', 'images'],
    version: '1.2.0',
    author: 'MediaKit',
  },
  {
    id: 'images-lightbox',
    name: 'Lightbox',
    description: 'Full-screen image overlay viewer with zoom and pan support.',
    category: 'images',
    icon: 'Maximize2',
    isInstalled: false,
    tags: ['lightbox', 'overlay', 'zoom', 'pan', 'viewer'],
    version: '1.1.0',
    author: 'MediaKit',
  },
  {
    id: 'images-avatar-group',
    name: 'Avatar Group',
    description: 'Overlapping avatar stacks showing team members and user presence.',
    category: 'images',
    icon: 'Users',
    isInstalled: false,
    tags: ['avatar', 'group', 'stack', 'team', 'presence'],
    version: '1.0.0',
    author: 'MediaKit',
  },
  {
    id: 'images-logo-placeholder',
    name: 'Logo Placeholder',
    description: 'Branded logo containers with text fallbacks and sizing presets.',
    category: 'images',
    icon: 'Bookmark',
    isInstalled: false,
    tags: ['logo', 'brand', 'placeholder', 'container', 'identity'],
    version: '1.0.0',
    author: 'MediaKit',
  },
  {
    id: 'images-screenshot-frame',
    name: 'Screenshot Frame',
    description: 'Device mockup frames for showcasing app screenshots.',
    category: 'images',
    icon: 'Smartphone',
    isInstalled: false,
    tags: ['screenshot', 'mockup', 'device', 'frame', 'browser'],
    version: '1.3.0',
    author: 'MediaKit',
  },

  // ── Colors (7) ──────────────────────────────────────────────
  {
    id: 'colors-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes from a seed color or randomly.',
    category: 'colors',
    icon: 'Palette',
    isInstalled: false,
    isPopular: true,
    tags: ['palette', 'harmony', 'generate', 'seed', 'colors'],
    version: '2.5.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'colors-gradient',
    name: 'Gradient Builder',
    description: 'Multi-stop gradient editor with angle and type controls.',
    category: 'colors',
    icon: 'PaintBucket',
    isInstalled: false,
    tags: ['gradient', 'linear', 'radial', 'stops', 'angle'],
    version: '2.0.0',
    author: 'ColorLab',
  },
  {
    id: 'colors-contrast',
    name: 'Contrast Checker',
    description: 'WCAG 2.1 contrast ratio checker for text and UI elements.',
    category: 'colors',
    icon: 'Eye',
    isInstalled: false,
    tags: ['contrast', 'wcag', 'a11y', 'ratio', 'readability'],
    version: '1.4.0',
    author: 'ColorLab',
  },
  {
    id: 'colors-blind-sim',
    name: 'Color Blind Simulator',
    description: 'Preview designs as seen with protanopia, deuteranopia, and tritanopia.',
    category: 'colors',
    icon: 'Eye',
    isInstalled: false,
    tags: ['color-blind', 'protanopia', 'deuteranopia', 'simulation', 'vision'],
    version: '1.2.0',
    author: 'ColorLab',
  },
  {
    id: 'colors-extractor',
    name: 'Palette Extractor',
    description: 'Extract dominant colors from uploaded images using k-means clustering.',
    category: 'colors',
    icon: 'Pencil',
    isInstalled: false,
    tags: ['extract', 'image', 'dominant', 'k-means', 'sampling'],
    version: '1.1.0',
    author: 'ColorLab',
  },
  {
    id: 'colors-theme-generator',
    name: 'Theme Generator',
    description: 'Generate light/dark theme color tokens from a single brand color.',
    category: 'colors',
    icon: 'Sparkles',
    isInstalled: false,
    tags: ['theme', 'dark-mode', 'tokens', 'brand', 'light-dark'],
    version: '1.3.0',
    author: 'DesignTokens',
  },
  {
    id: 'colors-brand',
    name: 'Brand Colors',
    description: 'Curated brand color palettes from popular companies and products.',
    category: 'colors',
    icon: 'Flag',
    isInstalled: false,
    tags: ['brand', 'company', 'curated', 'reference', 'palette'],
    version: '1.0.0',
    author: 'ColorLab',
  },

  // ── Export (7) ──────────────────────────────────────────────
  {
    id: 'export-png',
    name: 'PNG Export',
    description: 'Export canvas or selections as high-DPI PNG images.',
    category: 'export',
    icon: 'Download',
    isInstalled: false,
    isPopular: true,
    tags: ['png', 'image', 'raster', 'export', 'high-dpi'],
    version: '3.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'export-svg',
    name: 'SVG Export',
    description: 'Export vector drawings as clean, optimized SVG files.',
    category: 'export',
    icon: 'Code',
    isInstalled: false,
    tags: ['svg', 'vector', 'export', 'scalable', 'clean'],
    version: '2.5.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'export-pdf',
    name: 'PDF Export',
    description: 'Generate multi-page PDF documents with custom page sizes.',
    category: 'export',
    icon: 'FileText',
    isInstalled: false,
    isPopular: true,
    tags: ['pdf', 'document', 'print', 'multi-page', 'export'],
    version: '2.3.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'export-json',
    name: 'JSON Export',
    description: 'Export the canvas state as structured JSON for programmatic use.',
    category: 'export',
    icon: 'Clipboard',
    isInstalled: false,
    tags: ['json', 'data', 'state', 'serialize', 'backup'],
    version: '1.2.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'export-clipboard',
    name: 'Clipboard Copy',
    description: 'Copy canvas content or SVG code directly to the system clipboard.',
    category: 'export',
    icon: 'Copy',
    isInstalled: false,
    tags: ['clipboard', 'copy', 'paste', 'system', 'quick'],
    version: '1.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'export-code-gen',
    name: 'Code Generation',
    description: 'Generate React, Vue, or HTML/CSS code from canvas elements.',
    category: 'export',
    icon: 'Code',
    isInstalled: false,
    tags: ['code-gen', 'react', 'vue', 'html', 'developer'],
    version: '1.4.0',
    author: 'DevKit',
  },
  {
    id: 'export-css',
    name: 'CSS Export',
    description: 'Export design tokens, gradients, and shadows as CSS variables.',
    category: 'export',
    icon: 'SlidersHorizontal',
    isInstalled: false,
    tags: ['css', 'tokens', 'variables', 'styles', 'design-tokens'],
    version: '1.0.0',
    author: 'DevKit',
  },

  // ── Templates (6) ───────────────────────────────────────────
  {
    id: 'templates-landing',
    name: 'Landing Page',
    description: 'Conversion-optimized landing page template with hero and CTAs.',
    category: 'templates',
    icon: 'Layout',
    isInstalled: false,
    isPopular: true,
    tags: ['landing', 'hero', 'cta', 'conversion', 'page'],
    version: '2.0.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-dashboard',
    name: 'Dashboard',
    description: 'Analytics dashboard layout with KPI cards and chart panels.',
    category: 'templates',
    icon: 'BarChart3',
    isInstalled: false,
    tags: ['dashboard', 'analytics', 'kpi', 'charts', 'admin'],
    version: '2.1.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-blog',
    name: 'Blog Layout',
    description: 'Clean blog template with article list, sidebar, and reading view.',
    category: 'templates',
    icon: 'FileText',
    isInstalled: false,
    tags: ['blog', 'article', 'content', 'reading', 'sidebar'],
    version: '1.2.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-ecommerce',
    name: 'E-Commerce',
    description: 'Product listing and detail page templates with cart UI.',
    category: 'templates',
    icon: 'Box',
    isInstalled: false,
    tags: ['ecommerce', 'product', 'cart', 'listing', 'shop'],
    version: '1.3.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-portfolio',
    name: 'Portfolio',
    description: 'Creative portfolio layout with project gallery and about section.',
    category: 'templates',
    icon: 'Frame',
    isInstalled: false,
    tags: ['portfolio', 'creative', 'gallery', 'projects', 'personal'],
    version: '1.1.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-saas',
    name: 'SaaS App',
    description: 'Modern SaaS application shell with sidebar, header, and content area.',
    category: 'templates',
    icon: 'Monitor',
    isInstalled: false,
    tags: ['saas', 'app-shell', 'sidebar', 'header', 'modern'],
    version: '1.4.0',
    author: 'BranchBoard Templates',
  },

  // ── AI Tools (6) ────────────────────────────────────────────
  {
    id: 'ai-auto-layout',
    name: 'Auto Layout',
    description: 'AI-powered automatic arrangement of elements with smart spacing.',
    category: 'ai-tools',
    icon: 'Wand2',
    isInstalled: false,
    isPopular: true,
    tags: ['auto-layout', 'arrange', 'spacing', 'ai', 'smart'],
    version: '2.0.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-smart-arrange',
    name: 'Smart Arrange',
    description: 'One-click tidy-up that aligns and distributes elements evenly.',
    category: 'ai-tools',
    icon: 'Sparkles',
    isInstalled: false,
    tags: ['arrange', 'align', 'distribute', 'tidy', 'auto'],
    version: '1.5.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-content-generator',
    name: 'Content Generator',
    description: 'Generate realistic placeholder text, names, and data for mockups.',
    category: 'ai-tools',
    icon: 'Brain',
    isInstalled: false,
    tags: ['content', 'lorem', 'mockup', 'text', 'generate'],
    version: '1.3.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-style-transfer',
    name: 'Style Transfer',
    description: 'Apply visual styles from one design to another with a single click.',
    category: 'ai-tools',
    icon: 'PaintBucket',
    isInstalled: false,
    tags: ['style', 'transfer', 'apply', 'consistency', 'ai'],
    version: '1.0.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-color-suggest',
    name: 'Color Suggest',
    description: 'AI-recommended color combinations based on context and mood.',
    category: 'ai-tools',
    icon: 'Palette',
    isInstalled: false,
    tags: ['color', 'suggest', 'mood', 'ai', 'recommendation'],
    version: '1.1.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-wireframe-gen',
    name: 'Wireframe Generator',
    description: 'Generate wireframe layouts from a natural-language description.',
    category: 'ai-tools',
    icon: 'Bot',
    isInstalled: false,
    tags: ['wireframe', 'generate', 'nlp', 'ai', 'layout'],
    version: '0.9.0',
    author: 'BranchBoard AI',
  },

  // ── Collaboration (6) ───────────────────────────────────────
  {
    id: 'collab-comments',
    name: 'Comments',
    description: 'Pin contextual comments to specific canvas elements and regions.',
    category: 'collaboration',
    icon: 'MessageSquare',
    isInstalled: false,
    isPopular: true,
    tags: ['comments', 'feedback', 'pin', 'contextual', 'review'],
    version: '2.3.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'collab-annotations',
    name: 'Annotations',
    description: 'Drawing and markup tools for annotating designs with freehand ink.',
    category: 'collaboration',
    icon: 'Pencil',
    isInstalled: false,
    tags: ['annotation', 'markup', 'draw', 'ink', 'review'],
    version: '1.5.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'collab-version-compare',
    name: 'Version Compare',
    description: 'Side-by-side diff view comparing two canvas snapshots.',
    category: 'collaboration',
    icon: 'GitBranch',
    isInstalled: false,
    tags: ['version', 'compare', 'diff', 'history', 'snapshot'],
    version: '1.2.0',
    author: 'CollabKit',
  },
  {
    id: 'collab-review-mode',
    name: 'Review Mode',
    description: 'Lock editing and enable review-only mode with approval stamps.',
    category: 'collaboration',
    icon: 'Check',
    isInstalled: false,
    tags: ['review', 'approve', 'lock', 'readonly', 'stakeholder'],
    version: '1.1.0',
    author: 'CollabKit',
  },
  {
    id: 'collab-live-cursors',
    name: 'Live Cursors',
    description: 'See teammates\' real-time cursor positions and selections.',
    category: 'collaboration',
    icon: 'MousePointer',
    isInstalled: false,
    tags: ['cursor', 'real-time', 'presence', 'multiplayer', 'live'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'collab-presence',
    name: 'Presence Indicators',
    description: 'Avatars and status badges showing who is viewing the board.',
    category: 'collaboration',
    icon: 'Users',
    isInstalled: false,
    tags: ['presence', 'avatar', 'status', 'online', 'awareness'],
    version: '1.3.0',
    author: 'CollabKit',
  },

  // ── Accessibility (6) ───────────────────────────────────────
  {
    id: 'a11y-alt-text',
    name: 'Alt Text Generator',
    description: 'AI-assisted alt text suggestions for images and icons.',
    category: 'accessibility',
    icon: 'Eye',
    isInstalled: false,
    tags: ['alt-text', 'image', 'description', 'ai', 'screen-reader'],
    version: '1.3.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-focus-order',
    name: 'Focus Order Checker',
    description: 'Visualize and validate the tab focus order across components.',
    category: 'accessibility',
    icon: 'Target',
    isInstalled: false,
    tags: ['focus', 'tab-order', 'keyboard', 'navigation', 'a11y'],
    version: '1.2.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-aria-labels',
    name: 'ARIA Labels',
    description: 'Add and validate ARIA labels, roles, and descriptions on elements.',
    category: 'accessibility',
    icon: 'Shield',
    isInstalled: false,
    tags: ['aria', 'labels', 'roles', 'semantic', 'wai'],
    version: '1.1.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-color-contrast',
    name: 'Color Contrast Analyzer',
    description: 'Batch-check all text elements for WCAG AA/AAA compliance.',
    category: 'accessibility',
    icon: 'Eye',
    isInstalled: false,
    tags: ['contrast', 'wcag', 'aa', 'aaa', 'text'],
    version: '1.0.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-screen-reader',
    name: 'Screen Reader Preview',
    description: 'Preview how a screen reader would announce the design content.',
    category: 'accessibility',
    icon: 'Search',
    isInstalled: false,
    tags: ['screen-reader', 'announce', 'preview', 'assistive', 'audio'],
    version: '0.9.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-touch-targets',
    name: 'Touch Target Checker',
    description: 'Highlight interactive elements smaller than the 44px minimum.',
    category: 'accessibility',
    icon: 'Hand',
    isInstalled: false,
    tags: ['touch', 'target', '44px', 'mobile', 'minimum'],
    version: '1.0.0',
    author: 'A11yKit',
  },

  // ── Math (6) ────────────────────────────────────────────────
  {
    id: 'math-calculator',
    name: 'Calculator',
    description: 'On-canvas calculator for quick numerical computations.',
    category: 'math',
    icon: 'Calculator',
    isInstalled: false,
    isPopular: true,
    tags: ['calculator', 'compute', 'arithmetic', 'math', 'quick'],
    version: '1.4.0',
    author: 'MathKit',
  },
  {
    id: 'math-graph-plotter',
    name: 'Graph Plotter',
    description: 'Plot mathematical functions and equations on a coordinate grid.',
    category: 'math',
    icon: 'Zap',
    isInstalled: false,
    tags: ['graph', 'plot', 'function', 'equation', 'coordinate'],
    version: '1.3.0',
    author: 'MathKit',
  },
  {
    id: 'math-equation-editor',
    name: 'Equation Editor',
    description: 'LaTeX-based equation editor for mathematical notation.',
    category: 'math',
    icon: 'Pencil',
    isInstalled: false,
    tags: ['equation', 'latex', 'formula', 'notation', 'math'],
    version: '1.2.0',
    author: 'MathKit',
  },
  {
    id: 'math-geometry',
    name: 'Geometry Tools',
    description: 'Compass, protractor, and angle measurement overlays.',
    category: 'math',
    icon: 'Compass',
    isInstalled: false,
    tags: ['geometry', 'compass', 'protractor', 'angle', 'measure'],
    version: '1.1.0',
    author: 'MathKit',
  },
  {
    id: 'math-ruler',
    name: 'Ruler & Guides',
    description: 'Pixel and unit rulers with draggable guide lines.',
    category: 'math',
    icon: 'Ruler',
    isInstalled: false,
    tags: ['ruler', 'guides', 'measurement', 'pixel', 'align'],
    version: '1.0.0',
    author: 'MathKit',
  },
  {
    id: 'math-coordinate',
    name: 'Coordinate System',
    description: 'X-Y coordinate grid overlays with customizable origin and scale.',
    category: 'math',
    icon: 'Target',
    isInstalled: false,
    tags: ['coordinate', 'axes', 'grid', 'origin', 'scale'],
    version: '1.0.0',
    author: 'MathKit',
  },
  {
    id: 'math-design-calculator',
    name: 'Design Calculator',
    description: 'Quick calculator overlay for computing dimensions, spacing, and proportions.',
    category: 'math',
    icon: 'Calculator',
    isInstalled: false,
    tags: ['calculator', 'compute', 'dimensions', 'spacing', 'proportion'],
    version: '1.0.0',
    author: 'MathKit',
  },
]