export type PluginCategory = 'shapes' | 'charts' | 'icons' | 'layout' | 'wireframe' | 'diagrams' | 'text' | 'images' | 'colors' | 'export' | 'templates' | 'ai-tools' | 'collaboration' | 'accessibility' | 'math' | 'typography' | 'branding' | 'animation' | 'prototyping' | '3d' | 'illustration' | 'photo-editing' | 'responsive' | 'code-gen' | 'handoff'

export interface DesignPlugin {
  id: string
  name: string
  description: string
  category: PluginCategory
  icon: string // lucide icon name
  isInstalled: boolean
  isPopular?: boolean
  tags: string[]
  version: string
  author: string
}

export const PLUGIN_CATEGORIES: { id: PluginCategory; label: string }[] = [
  { id: 'shapes', label: 'Shapes' },
  { id: 'charts', label: 'Charts' },
  { id: 'icons', label: 'Icons' },
  { id: 'layout', label: 'Layout' },
  { id: 'wireframe', label: 'Wireframe' },
  { id: 'diagrams', label: 'Diagrams' },
  { id: 'text', label: 'Text' },
  { id: 'images', label: 'Images' },
  { id: 'colors', label: 'Colors' },
  { id: 'export', label: 'Export' },
  { id: 'templates', label: 'Templates' },
  { id: 'ai-tools', label: 'AI Tools' },
  { id: 'collaboration', label: 'Collaboration' },
  { id: 'accessibility', label: 'Accessibility' },
  { id: 'math', label: 'Math' },
  { id: 'typography', label: 'Typography' },
  { id: 'branding', label: 'Branding' },
  { id: 'animation', label: 'Animation' },
  { id: 'prototyping', label: 'Prototyping' },
  { id: '3d', label: '3D' },
  { id: 'illustration', label: 'Illustration' },
  { id: 'photo-editing', label: 'Photo Editing' },
  { id: 'responsive', label: 'Responsive' },
  { id: 'code-gen', label: 'Code Gen' },
  { id: 'handoff', label: 'Handoff' },
]

export const DESIGN_PLUGINS: DesignPlugin[] = [
  // ── Shapes (9) ──────────────────────────────────────────────
  {
    id: 'shapes-basic',
    name: 'Basic Shapes',
    description: 'Rectangles, circles, triangles, and other foundational geometric primitives.',
    category: 'shapes',
    icon: 'Box',
    isInstalled: true,
    isPopular: true,
    tags: ['rectangle', 'circle', 'triangle', 'geometry', 'fundamentals'],
    version: '2.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'shapes-polygons',
    name: 'Polygons',
    description: 'Regular polygons with configurable sides from triangles to dodecagons.',
    category: 'shapes',
    icon: 'Pentagon',
    isInstalled: true,
    tags: ['pentagon', 'octagon', 'heptagon', 'polygon', 'sides'],
    version: '1.4.0',
    author: 'OpenCanvas',
  },
  {
    id: 'shapes-stars',
    name: 'Stars & Bursts',
    description: 'Star shapes and radial burst effects for badges and highlights.',
    category: 'shapes',
    icon: 'Star',
    isInstalled: true,
    isPopular: true,
    tags: ['star', 'burst', 'badge', 'highlight', 'radial'],
    version: '1.3.0',
    author: 'OpenCanvas',
  },
  {
    id: 'shapes-arrows',
    name: 'Arrows & Connectors',
    description: 'Directional arrows, chevrons, and connector lines with custom endpoints.',
    category: 'shapes',
    icon: 'ArrowRight',
    isInstalled: true,
    tags: ['arrow', 'connector', 'direction', 'chevron', 'flow'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'shapes-speech-bubbles',
    name: 'Speech Bubbles',
    description: 'Chat and thought bubbles for dialogue and annotation on the canvas.',
    category: 'shapes',
    icon: 'MessageSquare',
    isInstalled: true,
    tags: ['bubble', 'chat', 'dialogue', 'annotation', 'speech'],
    version: '1.2.0',
    author: 'OpenCanvas',
  },
  {
    id: 'shapes-hexagons',
    name: 'Hexagons',
    description: 'Honeycomb-style hexagons perfect for diagrams and infographics.',
    category: 'shapes',
    icon: 'Hexagon',
    isInstalled: true,
    tags: ['hexagon', 'honeycomb', 'infographic', 'tessellation'],
    version: '1.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'shapes-badges',
    name: 'Badges & Ribbons',
    description: 'Decorative badge and ribbon shapes for labels and awards.',
    category: 'shapes',
    icon: 'Badge',
    isInstalled: true,
    tags: ['badge', 'ribbon', 'label', 'award', 'decorative'],
    version: '1.0.0',
    author: 'ShapeLab',
  },
  {
    id: 'shapes-curved-paths',
    name: 'Curved Paths',
    description: 'Bézier curves and smooth arc paths for organic shape creation.',
    category: 'shapes',
    icon: 'PenTool',
    isInstalled: false,
    isPopular: true,
    tags: ['bezier', 'curve', 'arc', 'path', 'organic'],
    version: '1.2.0',
    author: 'ShapeLab',
  },

  // ── Charts (8) ──────────────────────────────────────────────
  {
    id: 'charts-bar',
    name: 'Bar Chart',
    description: 'Vertical and horizontal bar charts for comparing discrete categories.',
    category: 'charts',
    icon: 'BarChart3',
    isInstalled: true,
    isPopular: true,
    tags: ['bar', 'chart', 'comparison', 'data', 'visualization'],
    version: '3.2.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'charts-line',
    name: 'Line Chart',
    description: 'Trend lines and multi-series area fills for time-series data.',
    category: 'charts',
    icon: 'LineChart',
    isInstalled: true,
    isPopular: true,
    tags: ['line', 'trend', 'time-series', 'area', 'graph'],
    version: '3.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'charts-pie',
    name: 'Pie & Donut Chart',
    description: 'Proportional slices showing part-to-whole relationships.',
    category: 'charts',
    icon: 'PieChart',
    isInstalled: true,
    tags: ['pie', 'donut', 'proportion', 'percentage', 'slice'],
    version: '2.4.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'charts-area',
    name: 'Area Chart',
    description: 'Stacked and layered area charts emphasizing volume over time.',
    category: 'charts',
    icon: 'Layers',
    isInstalled: true,
    tags: ['area', 'stacked', 'volume', 'filled', 'cumulative'],
    version: '1.5.0',
    author: 'ChartKit',
  },
  {
    id: 'charts-scatter',
    name: 'Scatter Plot',
    description: 'X-Y scatter plots revealing correlations and distribution clusters.',
    category: 'charts',
    icon: 'Target',
    isInstalled: true,
    tags: ['scatter', 'correlation', 'distribution', 'dot', 'xy'],
    version: '1.3.0',
    author: 'ChartKit',
  },
  {
    id: 'charts-radar',
    name: 'Radar Chart',
    description: 'Multi-axis radar/spider charts for comparing multiple metrics.',
    category: 'charts',
    icon: 'Compass',
    isInstalled: true,
    tags: ['radar', 'spider', 'multi-axis', 'comparison', 'polygon'],
    version: '1.2.0',
    author: 'ChartKit',
  },
  {
    id: 'charts-treemap',
    name: 'Treemap',
    description: 'Hierarchical nested rectangles sized by value for part-of-whole views.',
    category: 'charts',
    icon: 'Layout',
    isInstalled: true,
    tags: ['treemap', 'hierarchy', 'nested', 'proportion', 'rectangle'],
    version: '1.0.0',
    author: 'DataViz Lab',
  },
  {
    id: 'charts-funnel',
    name: 'Funnel Chart',
    description: 'Conversion funnel visualizations showing drop-off at each stage.',
    category: 'charts',
    icon: 'Filter',
    isInstalled: false,
    tags: ['funnel', 'conversion', 'drop-off', 'stages', 'pipeline'],
    version: '1.0.0',
    author: 'DataViz Lab',
  },

  // ── Icons (9) ───────────────────────────────────────────────
  {
    id: 'icons-lucide',
    name: 'Lucide Icons',
    description: 'Beautiful, consistent open-source icon set with 1,500+ icons.',
    category: 'icons',
    icon: 'Star',
    isInstalled: true,
    isPopular: true,
    tags: ['lucide', 'open-source', 'svg', 'icon-set', 'vector'],
    version: '0.460.0',
    author: 'Lucide Contributors',
  },
  {
    id: 'icons-font-awesome',
    name: 'Font Awesome',
    description: 'The web\'s most popular icon library with 2,000+ icons.',
    category: 'icons',
    icon: 'Heart',
    isInstalled: true,
    isPopular: true,
    tags: ['font-awesome', 'brands', 'solid', 'regular', 'classic'],
    version: '6.5.0',
    author: 'Font Awesome Team',
  },
  {
    id: 'icons-material',
    name: 'Material Design Icons',
    description: 'Google\'s Material icon set covering common UI actions and objects.',
    category: 'icons',
    icon: 'Globe',
    isInstalled: true,
    isPopular: true,
    tags: ['material', 'google', 'android', 'ui', 'design-system'],
    version: '7.4.0',
    author: 'Google Material',
  },
  {
    id: 'icons-heroicons',
    name: 'Heroicons',
    description: 'Crafted by the Tailwind Labs team, optimized for modern interfaces.',
    category: 'icons',
    icon: 'Sparkles',
    isInstalled: true,
    tags: ['heroicons', 'tailwind', 'outline', 'solid', 'modern'],
    version: '2.1.0',
    author: 'Tailwind Labs',
  },
  {
    id: 'icons-tabler',
    name: 'Tabler Icons',
    description: 'Over 5,000 pixel-perfect SVG icons with consistent styling.',
    category: 'icons',
    icon: 'Grid3X3',
    isInstalled: true,
    tags: ['tabler', 'svg', 'pixel-perfect', 'comprehensive', 'icons'],
    version: '3.6.0',
    author: 'Tabler',
  },
  {
    id: 'icons-phosphor',
    name: 'Phosphor Icons',
    description: 'Flexible icon family with six weights from thin to bold.',
    category: 'icons',
    icon: 'MousePointer',
    isInstalled: true,
    tags: ['phosphor', 'weights', 'flexible', 'family', 'variable'],
    version: '2.1.0',
    author: 'Phosphor Icons',
  },
  {
    id: 'icons-remix',
    name: 'Remix Icon',
    description: 'Neutral, system-symbolic icon set with 2,800+ icons.',
    category: 'icons',
    icon: 'RefreshCw',
    isInstalled: true,
    tags: ['remix', 'neutral', 'symbolic', 'line', 'fill'],
    version: '4.2.0',
    author: 'Remix Design',
  },
  {
    id: 'icons-bootstrap',
    name: 'Bootstrap Icons',
    description: 'Over 2,000 icons from the Bootstrap ecosystem in SVG format.',
    category: 'icons',
    icon: 'Grid3X3',
    isInstalled: false,
    tags: ['bootstrap', 'svg', 'ui', 'components', 'framework'],
    version: '1.11.0',
    author: 'Bootstrap Team',
  },

  // ── Layout (8) ──────────────────────────────────────────────
  {
    id: 'layout-grid',
    name: 'Grid System',
    description: '12-column and auto-fit grid overlays for precise element alignment.',
    category: 'layout',
    icon: 'Grid3X3',
    isInstalled: true,
    tags: ['grid', 'columns', 'alignment', 'overlay', 'structure'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'layout-flexbox',
    name: 'Flexbox Layout',
    description: 'Visual flexbox direction and distribution controls on the canvas.',
    category: 'layout',
    icon: 'Columns3',
    isInstalled: true,
    tags: ['flexbox', 'flex', 'direction', 'distribution', 'spacing'],
    version: '1.3.0',
    author: 'LayoutKit',
  },
  {
    id: 'layout-masonry',
    name: 'Masonry Layout',
    description: 'Pinterest-style masonry grids with variable-height cards.',
    category: 'layout',
    icon: 'Layout',
    isInstalled: true,
    tags: ['masonry', 'pinterest', 'waterfall', 'cards', 'variable'],
    version: '1.1.0',
    author: 'LayoutKit',
  },
  {
    id: 'layout-css-grid',
    name: 'CSS Grid Builder',
    description: 'Drag-and-drop grid template builder with named areas.',
    category: 'layout',
    icon: 'Frame',
    isInstalled: true,
    tags: ['css-grid', 'template', 'areas', 'builder', 'visual'],
    version: '1.0.0',
    author: 'LayoutKit',
  },
  {
    id: 'layout-responsive',
    name: 'Responsive Breakpoints',
    description: 'Preview and switch between mobile, tablet, and desktop viewports.',
    category: 'layout',
    icon: 'Monitor',
    isInstalled: false,
    tags: ['responsive', 'breakpoint', 'viewport', 'mobile', 'desktop'],
    version: '1.2.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'layout-spacing',
    name: 'Spacing System',
    description: 'Consistent 4px-based spacing scale with visual spacing ruler.',
    category: 'layout',
    icon: 'Move',
    isInstalled: false,
    tags: ['spacing', 'padding', 'margin', 'scale', 'consistency'],
    version: '1.0.0',
    author: 'DesignTokens',
  },
  {
    id: 'layout-auto-flow',
    name: 'Auto Flow Layout',
    description: 'Intelligent element flow that wraps and reflows as containers resize.',
    category: 'layout',
    icon: 'Workflow',
    isInstalled: false,
    tags: ['auto-flow', 'reflow', 'wrap', 'dynamic', 'container'],
    version: '1.1.0',
    author: 'LayoutKit',
  },
  {
    id: 'layout-snap-guides',
    name: 'Snap Guides',
    description: 'Smart alignment guides that appear when elements are near edges.',
    category: 'layout',
    icon: 'AlignCenterHorizontal',
    isInstalled: false,
    isPopular: true,
    tags: ['snap', 'guides', 'align', 'edges', 'magnetic'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },

  // ── Wireframe (8) ───────────────────────────────────────────
  {
    id: 'wireframe-inputs',
    name: 'Input Fields',
    description: 'Text inputs, textareas, selects, and checkboxes in wireframe style.',
    category: 'wireframe',
    icon: 'FormInput',
    isInstalled: false,
    tags: ['input', 'text-field', 'form', 'wireframe', 'skeleton'],
    version: '2.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'wireframe-buttons',
    name: 'Buttons',
    description: 'Primary, secondary, ghost, and icon button wireframe variants.',
    category: 'wireframe',
    icon: 'MousePointer',
    isInstalled: false,
    tags: ['button', 'cta', 'action', 'wireframe', 'interactive'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'wireframe-cards',
    name: 'Cards',
    description: 'Content cards with headers, bodies, images, and footer slots.',
    category: 'wireframe',
    icon: 'Layers',
    isInstalled: false,
    tags: ['card', 'content', 'container', 'wireframe', 'block'],
    version: '1.3.0',
    author: 'WireKit',
  },
  {
    id: 'wireframe-navbars',
    name: 'Navigation Bars',
    description: 'Top nav and breadcrumb bars with logo, links, and actions.',
    category: 'wireframe',
    icon: 'Navigation',
    isInstalled: false,
    tags: ['navbar', 'navigation', 'header', 'links', 'wireframe'],
    version: '1.2.0',
    author: 'WireKit',
  },
  {
    id: 'wireframe-forms',
    name: 'Form Builders',
    description: 'Complete form layouts with validation states and error messages.',
    category: 'wireframe',
    icon: 'Clipboard',
    isInstalled: false,
    tags: ['form', 'validation', 'error', 'submit', 'layout'],
    version: '1.1.0',
    author: 'WireKit',
  },
  {
    id: 'wireframe-tables',
    name: 'Data Tables',
    description: 'Sortable, paginated table wireframes with row actions.',
    category: 'wireframe',
    icon: 'Table',
    isInstalled: false,
    tags: ['table', 'data', 'sort', 'paginate', 'grid'],
    version: '1.0.0',
    author: 'WireKit',
  },
  {
    id: 'wireframe-modals',
    name: 'Modals & Dialogs',
    description: 'Overlay dialogs, drawers, and confirmation prompt wireframes.',
    category: 'wireframe',
    icon: 'Maximize2',
    isInstalled: false,
    tags: ['modal', 'dialog', 'drawer', 'overlay', 'prompt'],
    version: '1.2.0',
    author: 'WireKit',
  },
  {
    id: 'wireframe-footers',
    name: 'Footer Sections',
    description: 'Multi-column footer wireframes with links, social icons, and legal text.',
    category: 'wireframe',
    icon: 'Grip',
    isInstalled: false,
    tags: ['footer', 'links', 'social', 'legal', 'bottom'],
    version: '1.0.0',
    author: 'WireKit',
  },

  // ── Diagrams (8) ────────────────────────────────────────────
  {
    id: 'diagrams-flowchart',
    name: 'Flowchart',
    description: 'Process flow diagrams with decision nodes and loopback arrows.',
    category: 'diagrams',
    icon: 'Workflow',
    isInstalled: false,
    isPopular: true,
    tags: ['flowchart', 'process', 'decision', 'flow', 'logic'],
    version: '3.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'diagrams-uml-class',
    name: 'UML Class Diagram',
    description: 'Class boxes with attributes, methods, and relationship lines.',
    category: 'diagrams',
    icon: 'Layers',
    isInstalled: false,
    tags: ['uml', 'class', 'inheritance', 'methods', 'attributes'],
    version: '2.2.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-er',
    name: 'ER Diagram',
    description: 'Entity-relationship diagrams with cardinality notations.',
    category: 'diagrams',
    icon: 'GitBranch',
    isInstalled: false,
    tags: ['er', 'entity', 'relationship', 'database', 'schema'],
    version: '2.0.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-mind-map',
    name: 'Mind Map',
    description: 'Radial mind mapping with auto-layout and collapsible branches.',
    category: 'diagrams',
    icon: 'Lightbulb',
    isInstalled: false,
    tags: ['mind-map', 'radial', 'brainstorm', 'branches', 'hierarchy'],
    version: '2.1.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-org-chart',
    name: 'Org Chart',
    description: 'Organizational hierarchy trees with roles and reporting lines.',
    category: 'diagrams',
    icon: 'Users',
    isInstalled: false,
    tags: ['org-chart', 'hierarchy', 'organization', 'reporting', 'team'],
    version: '1.4.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-sequence',
    name: 'Sequence Diagram',
    description: 'Interaction sequences between actors with lifelines and messages.',
    category: 'diagrams',
    icon: 'ArrowRight',
    isInstalled: false,
    tags: ['sequence', 'interaction', 'lifeline', 'message', 'uml'],
    version: '1.3.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-state',
    name: 'State Diagram',
    description: 'Finite state machines with transitions and guard conditions.',
    category: 'diagrams',
    icon: 'RotateCw',
    isInstalled: false,
    tags: ['state', 'machine', 'transition', 'guard', 'fsm'],
    version: '1.2.0',
    author: 'DiagramForge',
  },
  {
    id: 'diagrams-gantt',
    name: 'Gantt Chart',
    description: 'Project timeline bars with dependencies, milestones, and resources.',
    category: 'diagrams',
    icon: 'Calendar',
    isInstalled: false,
    tags: ['gantt', 'timeline', 'project', 'milestone', 'schedule'],
    version: '1.0.0',
    author: 'DataViz Lab',
  },

  // ── Text (9) ────────────────────────────────────────────────
  {
    id: 'text-typography-scale',
    name: 'Typography Scale',
    description: 'Modular type scale with predefined size ratios and presets.',
    category: 'text',
    icon: 'Type',
    isInstalled: false,
    isPopular: true,
    tags: ['typography', 'scale', 'modular', 'ratio', 'sizes'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'text-headings',
    name: 'Heading Styles',
    description: 'H1 through H6 heading presets with weight and spacing.',
    category: 'text',
    icon: 'Heading',
    isInstalled: false,
    tags: ['heading', 'h1', 'h2', 'h3', 'title'],
    version: '1.5.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'text-body',
    name: 'Body Text',
    description: 'Paragraph and running text styles with optimal line height.',
    category: 'text',
    icon: 'FileText',
    isInstalled: false,
    tags: ['body', 'paragraph', 'readability', 'line-height', 'prose'],
    version: '1.3.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'text-caption',
    name: 'Captions & Overlines',
    description: 'Small text styles for captions, labels, and overlines.',
    category: 'text',
    icon: 'Minimize2',
    isInstalled: false,
    tags: ['caption', 'overline', 'small', 'label', 'subtle'],
    version: '1.1.0',
    author: 'TypeLab',
  },
  {
    id: 'text-blockquote',
    name: 'Blockquote',
    description: 'Styled blockquote elements with decorative borders and attribution.',
    category: 'text',
    icon: 'Quote',
    isInstalled: false,
    tags: ['blockquote', 'quote', 'attribution', 'emphasis', 'citation'],
    version: '1.0.0',
    author: 'TypeLab',
  },
  {
    id: 'text-code-block',
    name: 'Code Block',
    description: 'Syntax-highlighted code blocks with line numbers and copy button.',
    category: 'text',
    icon: 'Code',
    isInstalled: false,
    tags: ['code', 'syntax', 'programming', 'snippet', 'monospace'],
    version: '1.2.0',
    author: 'TypeLab',
  },
  {
    id: 'text-list-styles',
    name: 'List Styles',
    description: 'Bulleted, numbered, and custom marker list configurations.',
    category: 'text',
    icon: 'List',
    isInstalled: false,
    tags: ['list', 'bullet', 'numbered', 'marker', 'ordered'],
    version: '1.0.0',
    author: 'TypeLab',
  },
  {
    id: 'text-rich-text',
    name: 'Rich Text Editor',
    description: 'WYSIWYG text editing with bold, italic, links, and inline formatting.',
    category: 'text',
    icon: 'Bold',
    isInstalled: false,
    tags: ['rich-text', 'wysiwyg', 'formatting', 'inline', 'editing'],
    version: '1.1.0',
    author: 'TypeLab',
  },

  // ── Images (9) ──────────────────────────────────────────────
  {
    id: 'images-placeholder',
    name: 'Image Placeholder',
    description: 'Configurable placeholder images with custom dimensions and labels.',
    category: 'images',
    icon: 'Image',
    isInstalled: false,
    isPopular: true,
    tags: ['placeholder', 'dummy', 'dimensions', 'lorem-pixel', 'skeleton'],
    version: '2.2.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'images-photo-grid',
    name: 'Photo Grid',
    description: 'Drag-to-resize photo grid with configurable gaps and cropping.',
    category: 'images',
    icon: 'Grid3X3',
    isInstalled: false,
    tags: ['photo-grid', 'gallery', 'crop', 'gap', 'images'],
    version: '1.4.0',
    author: 'MediaKit',
  },
  {
    id: 'images-gallery',
    name: 'Gallery',
    description: 'Scrollable image gallery with thumbnails and navigation.',
    category: 'images',
    icon: 'Layers',
    isInstalled: false,
    tags: ['gallery', 'thumbnail', 'scroll', 'browse', 'images'],
    version: '1.2.0',
    author: 'MediaKit',
  },
  {
    id: 'images-lightbox',
    name: 'Lightbox',
    description: 'Full-screen image overlay viewer with zoom and pan support.',
    category: 'images',
    icon: 'Maximize2',
    isInstalled: false,
    tags: ['lightbox', 'overlay', 'zoom', 'pan', 'viewer'],
    version: '1.1.0',
    author: 'MediaKit',
  },
  {
    id: 'images-avatar-group',
    name: 'Avatar Group',
    description: 'Overlapping avatar stacks showing team members and user presence.',
    category: 'images',
    icon: 'Users',
    isInstalled: false,
    tags: ['avatar', 'group', 'stack', 'team', 'presence'],
    version: '1.0.0',
    author: 'MediaKit',
  },
  {
    id: 'images-logo-placeholder',
    name: 'Logo Placeholder',
    description: 'Branded logo containers with text fallbacks and sizing presets.',
    category: 'images',
    icon: 'Bookmark',
    isInstalled: false,
    tags: ['logo', 'brand', 'placeholder', 'container', 'identity'],
    version: '1.0.0',
    author: 'MediaKit',
  },
  {
    id: 'images-screenshot-frame',
    name: 'Screenshot Frame',
    description: 'Device mockup frames for showcasing app screenshots.',
    category: 'images',
    icon: 'Smartphone',
    isInstalled: false,
    tags: ['screenshot', 'mockup', 'device', 'frame', 'browser'],
    version: '1.3.0',
    author: 'MediaKit',
  },
  {
    id: 'images-unsplash-integration',
    name: 'Unsplash Integration',
    description: 'Search and insert free high-resolution photos from Unsplash.',
    category: 'images',
    icon: 'Camera',
    isInstalled: false,
    isPopular: true,
    tags: ['unsplash', 'stock', 'photos', 'free', 'high-resolution'],
    version: '1.2.0',
    author: 'MediaKit',
  },

  // ── Colors (8) ──────────────────────────────────────────────
  {
    id: 'colors-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes from a seed color or randomly.',
    category: 'colors',
    icon: 'Palette',
    isInstalled: false,
    isPopular: true,
    tags: ['palette', 'harmony', 'generate', 'seed', 'colors'],
    version: '2.5.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'colors-gradient',
    name: 'Gradient Builder',
    description: 'Multi-stop gradient editor with angle and type controls.',
    category: 'colors',
    icon: 'PaintBucket',
    isInstalled: false,
    tags: ['gradient', 'linear', 'radial', 'stops', 'angle'],
    version: '2.0.0',
    author: 'ColorLab',
  },
  {
    id: 'colors-contrast',
    name: 'Contrast Checker',
    description: 'WCAG 2.1 contrast ratio checker for text and UI elements.',
    category: 'colors',
    icon: 'Eye',
    isInstalled: false,
    tags: ['contrast', 'wcag', 'a11y', 'ratio', 'readability'],
    version: '1.4.0',
    author: 'ColorLab',
  },
  {
    id: 'colors-blind-sim',
    name: 'Color Blind Simulator',
    description: 'Preview designs as seen with protanopia, deuteranopia, and tritanopia.',
    category: 'colors',
    icon: 'Eye',
    isInstalled: false,
    tags: ['color-blind', 'protanopia', 'deuteranopia', 'simulation', 'vision'],
    version: '1.2.0',
    author: 'ColorLab',
  },
  {
    id: 'colors-extractor',
    name: 'Palette Extractor',
    description: 'Extract dominant colors from uploaded images using k-means clustering.',
    category: 'colors',
    icon: 'Pencil',
    isInstalled: false,
    tags: ['extract', 'image', 'dominant', 'k-means', 'sampling'],
    version: '1.1.0',
    author: 'ColorLab',
  },
  {
    id: 'colors-theme-generator',
    name: 'Theme Generator',
    description: 'Generate light/dark theme color tokens from a single brand color.',
    category: 'colors',
    icon: 'Sparkles',
    isInstalled: false,
    tags: ['theme', 'dark-mode', 'tokens', 'brand', 'light-dark'],
    version: '1.3.0',
    author: 'DesignTokens',
  },
  {
    id: 'colors-brand',
    name: 'Brand Colors',
    description: 'Curated brand color palettes from popular companies and products.',
    category: 'colors',
    icon: 'Flag',
    isInstalled: false,
    tags: ['brand', 'company', 'curated', 'reference', 'palette'],
    version: '1.0.0',
    author: 'ColorLab',
  },
  {
    id: 'colors-eyedropper',
    name: 'Color Eyedropper',
    description: 'Pick any color from the canvas or an imported image with precision.',
    category: 'colors',
    icon: 'Pipette',
    isInstalled: false,
    isPopular: true,
    tags: ['eyedropper', 'picker', 'sample', 'color', 'precision'],
    version: '1.0.0',
    author: 'ColorLab',
  },

  // ── Export (9) ──────────────────────────────────────────────
  {
    id: 'export-png',
    name: 'PNG Export',
    description: 'Export canvas or selections as high-DPI PNG images.',
    category: 'export',
    icon: 'Download',
    isInstalled: false,
    isPopular: true,
    tags: ['png', 'image', 'raster', 'export', 'high-dpi'],
    version: '3.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'export-svg',
    name: 'SVG Export',
    description: 'Export vector drawings as clean, optimized SVG files.',
    category: 'export',
    icon: 'Code',
    isInstalled: false,
    tags: ['svg', 'vector', 'export', 'scalable', 'clean'],
    version: '2.5.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'export-pdf',
    name: 'PDF Export',
    description: 'Generate multi-page PDF documents with custom page sizes.',
    category: 'export',
    icon: 'FileText',
    isInstalled: false,
    isPopular: true,
    tags: ['pdf', 'document', 'print', 'multi-page', 'export'],
    version: '2.3.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'export-json',
    name: 'JSON Export',
    description: 'Export the canvas state as structured JSON for programmatic use.',
    category: 'export',
    icon: 'Clipboard',
    isInstalled: false,
    tags: ['json', 'data', 'state', 'serialize', 'backup'],
    version: '1.2.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'export-clipboard',
    name: 'Clipboard Copy',
    description: 'Copy canvas content or SVG code directly to the system clipboard.',
    category: 'export',
    icon: 'Copy',
    isInstalled: false,
    tags: ['clipboard', 'copy', 'paste', 'system', 'quick'],
    version: '1.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'export-code-gen',
    name: 'Code Generation',
    description: 'Generate React, Vue, or HTML/CSS code from canvas elements.',
    category: 'export',
    icon: 'Code',
    isInstalled: false,
    tags: ['code-gen', 'react', 'vue', 'html', 'developer'],
    version: '1.4.0',
    author: 'DevKit',
  },
  {
    id: 'export-css',
    name: 'CSS Export',
    description: 'Export design tokens, gradients, and shadows as CSS variables.',
    category: 'export',
    icon: 'SlidersHorizontal',
    isInstalled: false,
    tags: ['css', 'tokens', 'variables', 'styles', 'design-tokens'],
    version: '1.0.0',
    author: 'DevKit',
  },
  {
    id: 'export-webp',
    name: 'WebP Export',
    description: 'Export optimized WebP images with adjustable compression quality.',
    category: 'export',
    icon: 'ImageMinus',
    isInstalled: false,
    tags: ['webp', 'optimize', 'compression', 'web', 'performance'],
    version: '1.1.0',
    author: 'DevKit',
  },
  {
    id: 'export-figma-import',
    name: 'Figma Import',
    description: 'Import Figma files and convert layers to native canvas elements.',
    category: 'export',
    icon: 'Upload',
    isInstalled: false,
    isPopular: true,
    tags: ['figma', 'import', 'convert', 'layers', 'migration'],
    version: '1.3.0',
    author: 'BranchBoard Core',
  },

  // ── Templates (8) ───────────────────────────────────────────
  {
    id: 'templates-landing',
    name: 'Landing Page',
    description: 'Conversion-optimized landing page template with hero and CTAs.',
    category: 'templates',
    icon: 'Layout',
    isInstalled: false,
    isPopular: true,
    tags: ['landing', 'hero', 'cta', 'conversion', 'page'],
    version: '2.0.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-dashboard',
    name: 'Dashboard',
    description: 'Analytics dashboard layout with KPI cards and chart panels.',
    category: 'templates',
    icon: 'BarChart3',
    isInstalled: false,
    tags: ['dashboard', 'analytics', 'kpi', 'charts', 'admin'],
    version: '2.1.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-blog',
    name: 'Blog Layout',
    description: 'Clean blog template with article list, sidebar, and reading view.',
    category: 'templates',
    icon: 'FileText',
    isInstalled: false,
    tags: ['blog', 'article', 'content', 'reading', 'sidebar'],
    version: '1.2.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-ecommerce',
    name: 'E-Commerce',
    description: 'Product listing and detail page templates with cart UI.',
    category: 'templates',
    icon: 'Box',
    isInstalled: false,
    tags: ['ecommerce', 'product', 'cart', 'listing', 'shop'],
    version: '1.3.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-portfolio',
    name: 'Portfolio',
    description: 'Creative portfolio layout with project gallery and about section.',
    category: 'templates',
    icon: 'Frame',
    isInstalled: false,
    tags: ['portfolio', 'creative', 'gallery', 'projects', 'personal'],
    version: '1.1.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-saas',
    name: 'SaaS App',
    description: 'Modern SaaS application shell with sidebar, header, and content area.',
    category: 'templates',
    icon: 'Monitor',
    isInstalled: false,
    tags: ['saas', 'app-shell', 'sidebar', 'header', 'modern'],
    version: '1.4.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-onboarding',
    name: 'Onboarding Flow',
    description: 'Multi-step onboarding wizard with progress indicator and welcome screens.',
    category: 'templates',
    icon: 'ChevronRight',
    isInstalled: false,
    tags: ['onboarding', 'wizard', 'steps', 'welcome', 'flow'],
    version: '1.0.0',
    author: 'BranchBoard Templates',
  },
  {
    id: 'templates-auth-screens',
    name: 'Auth Screens',
    description: 'Login, signup, forgot password, and social auth screen templates.',
    category: 'templates',
    icon: 'Lock',
    isInstalled: false,
    tags: ['auth', 'login', 'signup', 'password', 'social'],
    version: '1.1.0',
    author: 'BranchBoard Templates',
  },

  // ── AI Tools (8) ────────────────────────────────────────────
  {
    id: 'ai-auto-layout',
    name: 'Auto Layout',
    description: 'AI-powered automatic arrangement of elements with smart spacing.',
    category: 'ai-tools',
    icon: 'Wand2',
    isInstalled: false,
    isPopular: true,
    tags: ['auto-layout', 'arrange', 'spacing', 'ai', 'smart'],
    version: '2.0.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-smart-arrange',
    name: 'Smart Arrange',
    description: 'One-click tidy-up that aligns and distributes elements evenly.',
    category: 'ai-tools',
    icon: 'Sparkles',
    isInstalled: false,
    tags: ['arrange', 'align', 'distribute', 'tidy', 'auto'],
    version: '1.5.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-content-generator',
    name: 'Content Generator',
    description: 'Generate realistic placeholder text, names, and data for mockups.',
    category: 'ai-tools',
    icon: 'Brain',
    isInstalled: false,
    tags: ['content', 'lorem', 'mockup', 'text', 'generate'],
    version: '1.3.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-style-transfer',
    name: 'Style Transfer',
    description: 'Apply visual styles from one design to another with a single click.',
    category: 'ai-tools',
    icon: 'PaintBucket',
    isInstalled: false,
    tags: ['style', 'transfer', 'apply', 'consistency', 'ai'],
    version: '1.0.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-color-suggest',
    name: 'Color Suggest',
    description: 'AI-recommended color combinations based on context and mood.',
    category: 'ai-tools',
    icon: 'Palette',
    isInstalled: false,
    tags: ['color', 'suggest', 'mood', 'ai', 'recommendation'],
    version: '1.1.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-wireframe-gen',
    name: 'Wireframe Generator',
    description: 'Generate wireframe layouts from a natural-language description.',
    category: 'ai-tools',
    icon: 'Bot',
    isInstalled: false,
    tags: ['wireframe', 'generate', 'nlp', 'ai', 'layout'],
    version: '0.9.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-image-upscale',
    name: 'Image Upscaler',
    description: 'Upscale low-resolution images with AI-powered super-resolution.',
    category: 'ai-tools',
    icon: 'Maximize2',
    isInstalled: false,
    isPopular: true,
    tags: ['upscale', 'resolution', 'super-resolution', 'enhance', 'ai'],
    version: '1.2.0',
    author: 'BranchBoard AI',
  },
  {
    id: 'ai-background-remove',
    name: 'Background Remover',
    description: 'Automatically remove backgrounds from product photos and portraits.',
    category: 'ai-tools',
    icon: 'Scissors',
    isInstalled: false,
    isPopular: true,
    tags: ['background', 'remove', 'cutout', 'transparent', 'ai'],
    version: '1.1.0',
    author: 'BranchBoard AI',
  },

  // ── Collaboration (8) ───────────────────────────────────────
  {
    id: 'collab-comments',
    name: 'Comments',
    description: 'Pin contextual comments to specific canvas elements and regions.',
    category: 'collaboration',
    icon: 'MessageSquare',
    isInstalled: false,
    isPopular: true,
    tags: ['comments', 'feedback', 'pin', 'contextual', 'review'],
    version: '2.3.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'collab-annotations',
    name: 'Annotations',
    description: 'Drawing and markup tools for annotating designs with freehand ink.',
    category: 'collaboration',
    icon: 'Pencil',
    isInstalled: false,
    tags: ['annotation', 'markup', 'draw', 'ink', 'review'],
    version: '1.5.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'collab-version-compare',
    name: 'Version Compare',
    description: 'Side-by-side diff view comparing two canvas snapshots.',
    category: 'collaboration',
    icon: 'GitBranch',
    isInstalled: false,
    tags: ['version', 'compare', 'diff', 'history', 'snapshot'],
    version: '1.2.0',
    author: 'CollabKit',
  },
  {
    id: 'collab-review-mode',
    name: 'Review Mode',
    description: 'Lock editing and enable review-only mode with approval stamps.',
    category: 'collaboration',
    icon: 'Check',
    isInstalled: false,
    tags: ['review', 'approve', 'lock', 'readonly', 'stakeholder'],
    version: '1.1.0',
    author: 'CollabKit',
  },
  {
    id: 'collab-live-cursors',
    name: 'Live Cursors',
    description: 'See teammates\' real-time cursor positions and selections.',
    category: 'collaboration',
    icon: 'MousePointer',
    isInstalled: false,
    tags: ['cursor', 'real-time', 'presence', 'multiplayer', 'live'],
    version: '2.0.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'collab-presence',
    name: 'Presence Indicators',
    description: 'Avatars and status badges showing who is viewing the board.',
    category: 'collaboration',
    icon: 'Users',
    isInstalled: false,
    tags: ['presence', 'avatar', 'status', 'online', 'awareness'],
    version: '1.3.0',
    author: 'CollabKit',
  },
  {
    id: 'collab-sharing',
    name: 'Share Link',
    description: 'Generate shareable links with view and edit permission controls.',
    category: 'collaboration',
    icon: 'Share2',
    isInstalled: false,
    isPopular: true,
    tags: ['share', 'link', 'permissions', 'view', 'edit'],
    version: '2.1.0',
    author: 'BranchBoard Core',
  },
  {
    id: 'collab-activity-log',
    name: 'Activity Log',
    description: 'Track all changes made to the canvas with timestamps and authors.',
    category: 'collaboration',
    icon: 'Clock',
    isInstalled: false,
    tags: ['activity', 'log', 'history', 'timestamp', 'audit'],
    version: '1.0.0',
    author: 'CollabKit',
  },

  // ── Accessibility (8) ───────────────────────────────────────
  {
    id: 'a11y-alt-text',
    name: 'Alt Text Generator',
    description: 'AI-assisted alt text suggestions for images and icons.',
    category: 'accessibility',
    icon: 'Eye',
    isInstalled: false,
    tags: ['alt-text', 'image', 'description', 'ai', 'screen-reader'],
    version: '1.3.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-focus-order',
    name: 'Focus Order Checker',
    description: 'Visualize and validate the tab focus order across components.',
    category: 'accessibility',
    icon: 'Target',
    isInstalled: false,
    tags: ['focus', 'tab-order', 'keyboard', 'navigation', 'a11y'],
    version: '1.2.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-aria-labels',
    name: 'ARIA Labels',
    description: 'Add and validate ARIA labels, roles, and descriptions on elements.',
    category: 'accessibility',
    icon: 'Shield',
    isInstalled: false,
    tags: ['aria', 'labels', 'roles', 'semantic', 'wai'],
    version: '1.1.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-color-contrast',
    name: 'Color Contrast Analyzer',
    description: 'Batch-check all text elements for WCAG AA/AAA compliance.',
    category: 'accessibility',
    icon: 'Eye',
    isInstalled: false,
    tags: ['contrast', 'wcag', 'aa', 'aaa', 'text'],
    version: '1.0.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-screen-reader',
    name: 'Screen Reader Preview',
    description: 'Preview how a screen reader would announce the design content.',
    category: 'accessibility',
    icon: 'Search',
    isInstalled: false,
    tags: ['screen-reader', 'announce', 'preview', 'assistive', 'audio'],
    version: '0.9.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-touch-targets',
    name: 'Touch Target Checker',
    description: 'Highlight interactive elements smaller than the 44px minimum.',
    category: 'accessibility',
    icon: 'Hand',
    isInstalled: false,
    tags: ['touch', 'target', '44px', 'mobile', 'minimum'],
    version: '1.0.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-motion-safety',
    name: 'Motion Safety',
    description: 'Detect animations that may trigger vestibular disorders and offer alternatives.',
    category: 'accessibility',
    icon: 'Activity',
    isInstalled: false,
    isPopular: true,
    tags: ['motion', 'vestibular', 'reduced-motion', 'safety', 'animation'],
    version: '1.0.0',
    author: 'A11yKit',
  },
  {
    id: 'a11y-semantic-structure',
    name: 'Semantic Structure',
    description: 'Validate heading hierarchy, landmarks, and semantic HTML structure.',
    category: 'accessibility',
    icon: 'ListOrdered',
    isInstalled: false,
    tags: ['semantic', 'heading', 'landmark', 'html', 'structure'],
    version: '1.1.0',
    author: 'A11yKit',
  },

  // ── Math (9) ────────────────────────────────────────────────
  {
    id: 'math-calculator',
    name: 'Calculator',
    description: 'On-canvas calculator for quick numerical computations.',
    category: 'math',
    icon: 'Calculator',
    isInstalled: false,
    isPopular: true,
    tags: ['calculator', 'compute', 'arithmetic', 'math', 'quick'],
    version: '1.4.0',
    author: 'MathKit',
  },
  {
    id: 'math-graph-plotter',
    name: 'Graph Plotter',
    description: 'Plot mathematical functions and equations on a coordinate grid.',
    category: 'math',
    icon: 'Zap',
    isInstalled: false,
    tags: ['graph', 'plot', 'function', 'equation', 'coordinate'],
    version: '1.3.0',
    author: 'MathKit',
  },
  {
    id: 'math-equation-editor',
    name: 'Equation Editor',
    description: 'LaTeX-based equation editor for mathematical notation.',
    category: 'math',
    icon: 'Pencil',
    isInstalled: false,
    tags: ['equation', 'latex', 'formula', 'notation', 'math'],
    version: '1.2.0',
    author: 'MathKit',
  },
  {
    id: 'math-geometry',
    name: 'Geometry Tools',
    description: 'Compass, protractor, and angle measurement overlays.',
    category: 'math',
    icon: 'Compass',
    isInstalled: false,
    tags: ['geometry', 'compass', 'protractor', 'angle', 'measure'],
    version: '1.1.0',
    author: 'MathKit',
  },
  {
    id: 'math-ruler',
    name: 'Ruler & Guides',
    description: 'Pixel and unit rulers with draggable guide lines.',
    category: 'math',
    icon: 'Ruler',
    isInstalled: false,
    tags: ['ruler', 'guides', 'measurement', 'pixel', 'align'],
    version: '1.0.0',
    author: 'MathKit',
  },
  {
    id: 'math-coordinate',
    name: 'Coordinate System',
    description: 'X-Y coordinate grid overlays with customizable origin and scale.',
    category: 'math',
    icon: 'Target',
    isInstalled: false,
    tags: ['coordinate', 'axes', 'grid', 'origin', 'scale'],
    version: '1.0.0',
    author: 'MathKit',
  },
  {
    id: 'math-design-calculator',
    name: 'Design Calculator',
    description: 'Quick calculator overlay for computing dimensions, spacing, and proportions.',
    category: 'math',
    icon: 'Calculator',
    isInstalled: false,
    tags: ['calculator', 'compute', 'dimensions', 'spacing', 'proportion'],
    version: '1.0.0',
    author: 'MathKit',
  },
  {
    id: 'math-grid-overlay',
    name: 'Grid Overlay',
    description: 'Customizable grid overlays with rule-of-thirds and diagonal guides.',
    category: 'math',
    icon: 'Grid3X3',
    isInstalled: false,
    tags: ['grid', 'rule-of-thirds', 'diagonal', 'composition', 'overlay'],
    version: '1.1.0',
    author: 'MathKit',
  },

  // ── Typography (8) ─────────────────────────────────────────
  {
    id: 'typography-font-pair',
    name: 'Font Pairing',
    description: 'Curated font pairings that combine complementary typefaces for headings and body.',
    category: 'typography',
    icon: 'Type',
    isInstalled: false,
    isPopular: true,
    tags: ['font-pair', 'heading', 'body', 'complementary', 'typeface'],
    version: '2.0.0',
    author: 'TypeLab',
  },
  {
    id: 'typography-web-fonts',
    name: 'Web Font Loader',
    description: 'Browse and load Google Fonts directly onto the canvas with instant preview.',
    category: 'typography',
    icon: 'Globe',
    isInstalled: false,
    isPopular: true,
    tags: ['google-fonts', 'web-fonts', 'load', 'preview', 'browse'],
    version: '1.5.0',
    author: 'TypeLab',
  },
  {
    id: 'typography-kerning',
    name: 'Kerning Adjuster',
    description: 'Fine-tune letter spacing and kerning pairs for polished typography.',
    category: 'typography',
    icon: 'Move',
    isInstalled: false,
    tags: ['kerning', 'letter-spacing', 'tracking', 'polish', 'typography'],
    version: '1.2.0',
    author: 'TypeLab',
  },
  {
    id: 'typography-line-height',
    name: 'Line Height Calculator',
    description: 'Calculate optimal line-height based on font size for maximum readability.',
    category: 'typography',
    icon: 'Ruler',
    isInstalled: false,
    tags: ['line-height', 'leading', 'readability', 'calculate', 'optimal'],
    version: '1.1.0',
    author: 'TypeLab',
  },
  {
    id: 'typography-text-shadow',
    name: 'Text Effects',
    description: 'Apply shadows, outlines, gradients, and emboss effects to text layers.',
    category: 'typography',
    icon: 'Sparkles',
    isInstalled: false,
    tags: ['text-shadow', 'outline', 'gradient-text', 'emboss', 'effects'],
    version: '1.3.0',
    author: 'TypeLab',
  },
  {
    id: 'typography-vertical-text',
    name: 'Vertical Text',
    description: 'Create vertical text layouts for CJK languages and creative posters.',
    category: 'typography',
    icon: 'ArrowUp',
    isInstalled: false,
    tags: ['vertical', 'cjk', 'japanese', 'chinese', 'poster'],
    version: '1.0.0',
    author: 'TypeLab',
  },
  {
    id: 'typography-open-type',
    name: 'OpenType Features',
    description: 'Access ligatures, alternates, old-style numerals, and stylistic sets.',
    category: 'typography',
    icon: 'Settings',
    isInstalled: false,
    tags: ['opentype', 'ligatures', 'alternates', 'stylistic', 'numerals'],
    version: '1.0.0',
    author: 'TypeLab',
  },
  {
    id: 'typography-variable-fonts',
    name: 'Variable Fonts',
    description: 'Explore variable font axes including weight, width, and optical size.',
    category: 'typography',
    icon: 'SlidersHorizontal',
    isInstalled: false,
    isPopular: true,
    tags: ['variable-font', 'axes', 'weight', 'width', 'optical'],
    version: '1.4.0',
    author: 'TypeLab',
  },

  // ── Branding (8) ────────────────────────────────────────────
  {
    id: 'branding-logo-maker',
    name: 'Logo Maker',
    description: 'AI-assisted logo design with icons, typography, and layout suggestions.',
    category: 'branding',
    icon: 'Stamp',
    isInstalled: false,
    isPopular: true,
    tags: ['logo', 'design', 'ai', 'icon', 'typography'],
    version: '2.0.0',
    author: 'BrandForge',
  },
  {
    id: 'branding-brand-kit',
    name: 'Brand Kit Manager',
    description: 'Centralized brand kit with logos, colors, fonts, and usage guidelines.',
    category: 'branding',
    icon: 'Folder',
    isInstalled: false,
    isPopular: true,
    tags: ['brand-kit', 'guidelines', 'logo', 'assets', 'consistency'],
    version: '1.5.0',
    author: 'BrandForge',
  },
  {
    id: 'branding-social-media',
    name: 'Social Media Templates',
    description: 'Pre-sized templates for Instagram, Twitter, LinkedIn, and other platforms.',
    category: 'branding',
    icon: 'Share2',
    isInstalled: false,
    isPopular: true,
    tags: ['social-media', 'instagram', 'templates', 'platform', 'sized'],
    version: '1.3.0',
    author: 'BrandForge',
  },
  {
    id: 'branding-business-card',
    name: 'Business Card',
    description: 'Professional business card templates with front and back layouts.',
    category: 'branding',
    icon: 'CreditCard',
    isInstalled: false,
    tags: ['business-card', 'print', 'professional', 'contact', 'template'],
    version: '1.2.0',
    author: 'BrandForge',
  },
  {
    id: 'branding-letterhead',
    name: 'Letterhead',
    description: 'Corporate letterhead templates with logo placement and branded colors.',
    category: 'branding',
    icon: 'FileText',
    isInstalled: false,
    tags: ['letterhead', 'corporate', 'stationery', 'print', 'branded'],
    version: '1.0.0',
    author: 'BrandForge',
  },
  {
    id: 'branding-style-guide',
    name: 'Style Guide Generator',
    description: 'Auto-generate a visual style guide from your design tokens and components.',
    category: 'branding',
    icon: 'Book',
    isInstalled: false,
    isPopular: true,
    tags: ['style-guide', 'design-system', 'tokens', 'documentation', 'auto-generate'],
    version: '1.4.0',
    author: 'BrandForge',
  },
  {
    id: 'branding-favicon',
    name: 'Favicon Generator',
    description: 'Generate favicons and app icons in all required sizes from one source.',
    category: 'branding',
    icon: 'Globe',
    isInstalled: false,
    tags: ['favicon', 'app-icon', 'ico', 'pwa', 'multi-size'],
    version: '1.1.0',
    author: 'BrandForge',
  },
  {
    id: 'branding-watermark',
    name: 'Watermark Tool',
    description: 'Apply branded watermarks and copyright notices to design exports.',
    category: 'branding',
    icon: 'Shield',
    isInstalled: false,
    tags: ['watermark', 'copyright', 'protect', 'brand', 'overlay'],
    version: '1.0.0',
    author: 'BrandForge',
  },

  // ── Animation (8) ────────────────────────────────────────────
  {
    id: 'animation-fade-in',
    name: 'Fade & Dissolve',
    description: 'Smooth fade-in, fade-out, and cross-dissolve transitions for elements.',
    category: 'animation',
    icon: 'Eye',
    isInstalled: false,
    isPopular: true,
    tags: ['fade', 'dissolve', 'opacity', 'transition', 'smooth'],
    version: '1.3.0',
    author: 'MotionKit',
  },
  {
    id: 'animation-slide-in',
    name: 'Slide Transitions',
    description: 'Directional slide animations from any edge with customizable easing.',
    category: 'animation',
    icon: 'ArrowRight',
    isInstalled: false,
    tags: ['slide', 'direction', 'easing', 'translate', 'enter'],
    version: '1.2.0',
    author: 'MotionKit',
  },
  {
    id: 'animation-scale-bounce',
    name: 'Scale & Bounce',
    description: 'Elastic scale, bounce, and spring animations with overshoot controls.',
    category: 'animation',
    icon: 'Maximize2',
    isInstalled: false,
    tags: ['scale', 'bounce', 'spring', 'elastic', 'overshoot'],
    version: '1.1.0',
    author: 'MotionKit',
  },
  {
    id: 'animation-micro-interactions',
    name: 'Micro Interactions',
    description: 'Button ripples, toggle switches, and small feedback animations.',
    category: 'animation',
    icon: 'MousePointerClick',
    isInstalled: false,
    isPopular: true,
    tags: ['micro', 'interaction', 'ripple', 'toggle', 'feedback'],
    version: '2.0.0',
    author: 'MotionKit',
  },
  {
    id: 'animation-scroll-trigger',
    name: 'Scroll Animations',
    description: 'Trigger animations when elements enter the viewport on scroll.',
    category: 'animation',
    icon: 'ChevronDown',
    isInstalled: false,
    isPopular: true,
    tags: ['scroll', 'trigger', 'viewport', 'reveal', 'parallax'],
    version: '1.4.0',
    author: 'MotionKit',
  },
  {
    id: 'animation-spinner',
    name: 'Loading Spinners',
    description: 'Pre-built loading spinners, progress bars, and skeleton animations.',
    category: 'animation',
    icon: 'RefreshCw',
    isInstalled: false,
    tags: ['spinner', 'loading', 'progress', 'skeleton', 'indicator'],
    version: '1.0.0',
    author: 'MotionKit',
  },
  {
    id: 'animation-path-animate',
    name: 'Path Animation',
    description: 'Animate objects along custom Bézier and SVG motion paths.',
    category: 'animation',
    icon: 'Spline',
    isInstalled: false,
    isPopular: true,
    tags: ['path', 'motion', 'bezier', 'animate-along', 'route'],
    version: '1.2.0',
    author: 'MotionKit',
  },
  {
    id: 'animation-stagger',
    name: 'Stagger Effects',
    description: 'Sequential stagger animations for lists and grouped elements.',
    category: 'animation',
    icon: 'List',
    isInstalled: false,
    tags: ['stagger', 'sequential', 'delay', 'group', 'list'],
    version: '1.1.0',
    author: 'MotionKit',
  },

  // ── Prototyping (8) ────────────────────────────────────────
  {
    id: 'prototyping-click-through',
    name: 'Click-through Prototype',
    description: 'Link screens together with tap and click hotspots for flow testing.',
    category: 'prototyping',
    icon: 'MousePointerClick',
    isInstalled: false,
    isPopular: true,
    tags: ['click-through', 'hotspot', 'screens', 'flow', 'testing'],
    version: '2.1.0',
    author: 'ProtoKit',
  },
  {
    id: 'prototyping-transitions',
    name: 'Screen Transitions',
    description: 'Add push, slide, and fade transitions between prototype screens.',
    category: 'prototyping',
    icon: 'ArrowRight',
    isInstalled: false,
    tags: ['transition', 'push', 'slide', 'fade', 'navigate'],
    version: '1.5.0',
    author: 'ProtoKit',
  },
  {
    id: 'prototyping-interactive-states',
    name: 'Interactive States',
    description: 'Define hover, pressed, disabled, and focused states for UI components.',
    category: 'prototyping',
    icon: 'MousePointer',
    isInstalled: false,
    isPopular: true,
    tags: ['hover', 'pressed', 'disabled', 'focused', 'states'],
    version: '1.3.0',
    author: 'ProtoKit',
  },
  {
    id: 'prototyping-form-inputs',
    name: 'Form Interactions',
    description: 'Simulate form typing, validation, and submission flows in prototypes.',
    category: 'prototyping',
    icon: 'Clipboard',
    isInstalled: false,
    tags: ['form', 'typing', 'validation', 'submission', 'simulate'],
    version: '1.2.0',
    author: 'ProtoKit',
  },
  {
    id: 'prototyping-scroll-sim',
    name: 'Scroll Simulation',
    description: 'Simulate vertical and horizontal scroll behavior in prototype frames.',
    category: 'prototyping',
    icon: 'ChevronsLeftRight',
    isInstalled: false,
    isPopular: true,
    tags: ['scroll', 'simulate', 'vertical', 'horizontal', 'overflow'],
    version: '1.4.0',
    author: 'ProtoKit',
  },
  {
    id: 'prototyping-device-frame',
    name: 'Device Frames',
    description: 'Wrap prototypes in realistic device frames for iPhone, Android, and desktop.',
    category: 'prototyping',
    icon: 'Smartphone',
    isInstalled: false,
    tags: ['device', 'frame', 'iphone', 'android', 'mockup'],
    version: '1.1.0',
    author: 'ProtoKit',
  },
  {
    id: 'prototyping-conditionals',
    name: 'Conditional Logic',
    description: 'Add if/then branching logic based on user interactions in prototypes.',
    category: 'prototyping',
    icon: 'GitBranch',
    isInstalled: false,
    tags: ['conditional', 'logic', 'branch', 'if-then', 'decision'],
    version: '1.0.0',
    author: 'ProtoKit',
  },
  {
    id: 'prototyping-variable-data',
    name: 'Variable Data',
    description: 'Use variables and expressions to drive dynamic content in prototypes.',
    category: 'prototyping',
    icon: 'Braces',
    isInstalled: false,
    tags: ['variable', 'data', 'dynamic', 'expression', 'binding'],
    version: '1.2.0',
    author: 'ProtoKit',
  },

  // ── 3D (8) ──────────────────────────────────────────────────
  {
    id: 'three-d-shapes',
    name: '3D Primitives',
    description: 'Cubes, spheres, cylinders, and cones rendered as isometric shapes.',
    category: '3d',
    icon: 'Box',
    isInstalled: false,
    isPopular: true,
    tags: ['3d', 'cube', 'sphere', 'cylinder', 'isometric'],
    version: '1.4.0',
    author: '3DForge',
  },
  {
    id: 'three-d-isometric',
    name: 'Isometric Grid',
    description: 'Isometric dot grid and guide overlays for 3D-style illustration.',
    category: '3d',
    icon: 'Grid3X3',
    isInstalled: false,
    tags: ['isometric', 'grid', 'dot', '3d', 'perspective'],
    version: '1.2.0',
    author: '3DForge',
  },
  {
    id: 'three-d-perspective',
    name: 'Perspective Transform',
    description: 'Apply perspective and 3D rotation transforms to flat 2D elements.',
    category: '3d',
    icon: 'RotateCw',
    isInstalled: false,
    tags: ['perspective', 'rotate', 'transform', '3d', 'depth'],
    version: '1.3.0',
    author: '3DForge',
  },
  {
    id: 'three-d-shadows',
    name: '3D Shadow System',
    description: 'Realistic drop shadows and ambient occlusion for depth perception.',
    category: '3d',
    icon: 'Layers',
    isInstalled: false,
    tags: ['shadow', 'ambient-occlusion', 'depth', 'realistic', 'layering'],
    version: '1.1.0',
    author: '3DForge',
  },
  {
    id: 'three-d-extrude',
    name: 'Extrude & Bevel',
    description: 'Give flat shapes depth with extrusion, bevel, and revolve effects.',
    category: '3d',
    icon: 'Maximize2',
    isInstalled: false,
    isPopular: true,
    tags: ['extrude', 'bevel', 'revolve', 'depth', '3d-effect'],
    version: '1.0.0',
    author: '3DForge',
  },
  {
    id: 'three-d-ambient',
    name: 'Ambient Lighting',
    description: 'Simulate directional lighting and ambient glow on canvas objects.',
    category: '3d',
    icon: 'Sun',
    isInstalled: false,
    tags: ['lighting', 'ambient', 'directional', 'glow', 'simulate'],
    version: '1.0.0',
    author: '3DForge',
  },
  {
    id: 'three-d-glassmorphism',
    name: 'Glassmorphism',
    description: 'Create frosted glass, translucent panels, and blur-behind effects.',
    category: '3d',
    icon: 'Sparkles',
    isInstalled: false,
    isPopular: true,
    tags: ['glassmorphism', 'frosted-glass', 'blur', 'translucent', 'modern'],
    version: '1.2.0',
    author: '3DForge',
  },
  {
    id: 'three-d-neumorphism',
    name: 'Neumorphism',
    description: 'Soft UI with inner and outer shadows creating raised or pressed effects.',
    category: '3d',
    icon: 'Circle',
    isInstalled: false,
    tags: ['neumorphism', 'soft-ui', 'raised', 'pressed', 'shadows'],
    version: '1.1.0',
    author: '3DForge',
  },

  // ── Illustration (8) ───────────────────────────────────────
  {
    id: 'illustration-stickers',
    name: 'Sticker Pack',
    description: 'Hand-drawn style stickers and decorative elements for playful designs.',
    category: 'illustration',
    icon: 'Star',
    isInstalled: false,
    isPopular: true,
    tags: ['sticker', 'hand-drawn', 'playful', 'decorative', 'illustration'],
    version: '1.3.0',
    author: 'Illustro',
  },
  {
    id: 'illustration-patterns',
    name: 'Pattern Library',
    description: 'Seamless patterns including geometric, organic, and textile designs.',
    category: 'illustration',
    icon: 'Layers',
    isInstalled: false,
    tags: ['pattern', 'seamless', 'geometric', 'organic', 'textile'],
    version: '1.2.0',
    author: 'Illustro',
  },
  {
    id: 'illustration-avatars',
    name: 'Avatar Builder',
    description: 'Mix-and-match avatar components for creating custom character illustrations.',
    category: 'illustration',
    icon: 'User',
    isInstalled: false,
    isPopular: true,
    tags: ['avatar', 'character', 'mix-match', 'illustration', 'custom'],
    version: '1.1.0',
    author: 'Illustro',
  },
  {
    id: 'illustration-scene-builder',
    name: 'Scene Builder',
    description: 'Drag-and-drop people, objects, and backgrounds to create custom scenes.',
    category: 'illustration',
    icon: 'Puzzle',
    isInstalled: false,
    isPopular: true,
    tags: ['scene', 'compose', 'people', 'objects', 'background'],
    version: '1.4.0',
    author: 'Illustro',
  },
  {
    id: 'illustration-doodle',
    name: 'Doodle Kit',
    description: 'Freehand doodle brushes and sketchy line styles for informal illustrations.',
    category: 'illustration',
    icon: 'Pen',
    isInstalled: false,
    tags: ['doodle', 'freehand', 'sketch', 'informal', 'brush'],
    version: '1.0.0',
    author: 'Illustro',
  },
  {
    id: 'illustration-isometric-people',
    name: 'Isometric People',
    description: 'Isometric character illustrations in various poses and professions.',
    category: 'illustration',
    icon: 'Users',
    isInstalled: false,
    tags: ['isometric', 'people', 'character', 'pose', 'profession'],
    version: '1.2.0',
    author: 'Illustro',
  },
  {
    id: 'illustration-icons-hand-drawn',
    name: 'Hand-Drawn Icons',
    description: 'Sketched and hand-drawn icon set for warm, approachable interfaces.',
    category: 'illustration',
    icon: 'PenTool',
    isInstalled: false,
    tags: ['hand-drawn', 'sketch', 'icon', 'warm', 'approachable'],
    version: '1.1.0',
    author: 'Illustro',
  },
  {
    id: 'illustration-nature',
    name: 'Nature Elements',
    description: 'Trees, mountains, clouds, and flora illustrations for background scenes.',
    category: 'illustration',
    icon: 'Mountain',
    isInstalled: false,
    tags: ['nature', 'trees', 'mountains', 'clouds', 'flora'],
    version: '1.0.0',
    author: 'Illustro',
  },

  // ── Photo Editing (8) ───────────────────────────────────────
  {
    id: 'photo-editing-filters',
    name: 'Photo Filters',
    description: 'Instagram-style photo filters with adjustable intensity sliders.',
    category: 'photo-editing',
    icon: 'Palette',
    isInstalled: false,
    isPopular: true,
    tags: ['filter', 'photo', 'instagram', 'adjust', 'intensity'],
    version: '1.4.0',
    author: 'PhotoKit',
  },
  {
    id: 'photo-editing-crop',
    name: 'Smart Crop',
    description: 'AI-powered crop suggestions based on subject detection and composition rules.',
    category: 'photo-editing',
    icon: 'Crop',
    isInstalled: false,
    tags: ['crop', 'smart', 'ai', 'composition', 'subject'],
    version: '1.2.0',
    author: 'PhotoKit',
  },
  {
    id: 'photo-editing-adjustments',
    name: 'Image Adjustments',
    description: 'Brightness, contrast, saturation, and hue sliders for photo correction.',
    category: 'photo-editing',
    icon: 'SlidersHorizontal',
    isInstalled: false,
    tags: ['brightness', 'contrast', 'saturation', 'hue', 'adjustment'],
    version: '1.3.0',
    author: 'PhotoKit',
  },
  {
    id: 'photo-editing-blur',
    name: 'Blur & Bokeh',
    description: 'Background blur, tilt-shift, and bokeh effects for depth of field.',
    category: 'photo-editing',
    icon: 'Aperture',
    isInstalled: false,
    isPopular: true,
    tags: ['blur', 'bokeh', 'tilt-shift', 'depth-of-field', 'background'],
    version: '1.1.0',
    author: 'PhotoKit',
  },
  {
    id: 'photo-editing-clone',
    name: 'Clone Stamp',
    description: 'Clone and heal tool for removing blemishes and duplicating areas.',
    category: 'photo-editing',
    icon: 'Copy',
    isInstalled: false,
    tags: ['clone', 'stamp', 'heal', 'blemish', 'duplicate'],
    version: '1.0.0',
    author: 'PhotoKit',
  },
  {
    id: 'photo-editing-duotone',
    name: 'Duotone Effect',
    description: 'Map photos to two-color gradients for striking visual treatments.',
    category: 'photo-editing',
    icon: 'CircleDot',
    isInstalled: false,
    tags: ['duotone', 'gradient', 'two-tone', 'visual', 'treatment'],
    version: '1.0.0',
    author: 'PhotoKit',
  },
  {
    id: 'photo-editing-vignette',
    name: 'Vignette & Overlay',
    description: 'Add vignette, light leaks, and texture overlays to photos.',
    category: 'photo-editing',
    icon: 'Focus',
    isInstalled: false,
    tags: ['vignette', 'light-leak', 'texture', 'overlay', 'film'],
    version: '1.1.0',
    author: 'PhotoKit',
  },
  {
    id: 'photo-editing-retouch',
    name: 'Portrait Retouch',
    description: 'Smooth skin, whiten teeth, and enhance eyes with AI-powered portrait tools.',
    category: 'photo-editing',
    icon: 'ScanFace',
    isInstalled: false,
    isPopular: true,
    tags: ['portrait', 'retouch', 'skin', 'enhance', 'ai'],
    version: '1.2.0',
    author: 'PhotoKit',
  },

  // ── Responsive (8) ──────────────────────────────────────────
  {
    id: 'responsive-breakpoints',
    name: 'Breakpoint Manager',
    description: 'Define and manage responsive breakpoints with live canvas resizing.',
    category: 'responsive',
    icon: 'Monitor',
    isInstalled: false,
    isPopular: true,
    tags: ['breakpoint', 'responsive', 'resize', 'live', 'viewport'],
    version: '1.5.0',
    author: 'ResponsiveKit',
  },
  {
    id: 'responsive-device-preview',
    name: 'Device Preview',
    description: 'Preview designs in device frames for phone, tablet, laptop, and desktop.',
    category: 'responsive',
    icon: 'Smartphone',
    isInstalled: false,
    isPopular: true,
    tags: ['device', 'preview', 'phone', 'tablet', 'desktop'],
    version: '2.0.0',
    author: 'ResponsiveKit',
  },
  {
    id: 'responsive-fluid-typography',
    name: 'Fluid Typography',
    description: 'Scale typography fluidly between min and max sizes across breakpoints.',
    category: 'responsive',
    icon: 'Type',
    isInstalled: false,
    isPopular: true,
    tags: ['fluid', 'typography', 'scale', 'responsive', 'clamp'],
    version: '1.2.0',
    author: 'ResponsiveKit',
  },
  {
    id: 'responsive-container-queries',
    name: 'Container Queries',
    description: 'Simulate CSS container query behavior for component-level responsiveness.',
    category: 'responsive',
    icon: 'Box',
    isInstalled: false,
    tags: ['container-query', 'component', 'responsive', 'css', 'inline'],
    version: '1.0.0',
    author: 'ResponsiveKit',
  },
  {
    id: 'responsive-layout-switcher',
    name: 'Layout Switcher',
    description: 'Toggle between single-column, multi-column, and grid layouts per breakpoint.',
    category: 'responsive',
    icon: 'Columns',
    isInstalled: false,
    tags: ['layout', 'switch', 'column', 'grid', 'responsive'],
    version: '1.1.0',
    author: 'ResponsiveKit',
  },
  {
    id: 'responsive-hide-show',
    name: 'Show/Hide Layers',
    description: 'Control which layers are visible at each breakpoint for responsive designs.',
    category: 'responsive',
    icon: 'Eye',
    isInstalled: false,
    tags: ['show-hide', 'visibility', 'layer', 'breakpoint', 'responsive'],
    version: '1.0.0',
    author: 'ResponsiveKit',
  },
  {
    id: 'responsive-media-query',
    name: 'Media Query Preview',
    description: 'Type custom media queries and instantly preview the matching viewport.',
    category: 'responsive',
    icon: 'Search',
    isInstalled: false,
    tags: ['media-query', 'custom', 'preview', 'css', 'viewport'],
    version: '1.1.0',
    author: 'ResponsiveKit',
  },
  {
    id: 'responsive-pinch-zoom',
    name: 'Pinch Zoom Preview',
    description: 'Test touch pinch-zoom behavior on responsive canvas previews.',
    category: 'responsive',
    icon: 'Maximize2',
    isInstalled: false,
    tags: ['pinch', 'zoom', 'touch', 'mobile', 'gesture'],
    version: '1.0.0',
    author: 'ResponsiveKit',
  },

  // ── Code Gen (8) ───────────────────────────────────────────
  {
    id: 'code-gen-react',
    name: 'React Component Gen',
    description: 'Generate clean React/Next.js component code with Tailwind CSS from designs.',
    category: 'code-gen',
    icon: 'Code',
    isInstalled: false,
    isPopular: true,
    tags: ['react', 'nextjs', 'tailwind', 'component', 'generate'],
    version: '2.0.0',
    author: 'DevKit',
  },
  {
    id: 'code-gen-vue',
    name: 'Vue Component Gen',
    description: 'Export designs as Vue 3 SFC components with scoped styles.',
    category: 'code-gen',
    icon: 'Code',
    isInstalled: false,
    tags: ['vue', 'sfc', 'component', 'scoped-styles', 'generate'],
    version: '1.3.0',
    author: 'DevKit',
  },
  {
    id: 'code-gen-html-css',
    name: 'HTML/CSS Export',
    description: 'Convert canvas elements to semantic HTML with clean inline or external CSS.',
    category: 'code-gen',
    icon: 'FileText',
    isInstalled: false,
    isPopular: true,
    tags: ['html', 'css', 'semantic', 'clean', 'export'],
    version: '2.1.0',
    author: 'DevKit',
  },
  {
    id: 'code-gen-tokens',
    name: 'Design Token Export',
    description: 'Export colors, spacing, and typography as JSON, CSS, or SCSS tokens.',
    category: 'code-gen',
    icon: 'Braces',
    isInstalled: false,
    tags: ['tokens', 'json', 'scss', 'variables', 'design-tokens'],
    version: '1.2.0',
    author: 'DevKit',
  },
  {
    id: 'code-gen-storybook',
    name: 'Storybook Stories',
    description: 'Auto-generate Storybook stories for each component on the canvas.',
    category: 'code-gen',
    icon: 'Book',
    isInstalled: false,
    isPopular: true,
    tags: ['storybook', 'stories', 'component', 'documentation', 'auto'],
    version: '1.1.0',
    author: 'DevKit',
  },
  {
    id: 'code-gen-tailwind',
    name: 'Tailwind Config',
    description: 'Generate a tailwind.config.js with colors, spacing, and fonts from the design.',
    category: 'code-gen',
    icon: 'Wind',
    isInstalled: false,
    tags: ['tailwind', 'config', 'theme', 'colors', 'spacing'],
    version: '1.4.0',
    author: 'DevKit',
  },
  {
    id: 'code-gen-svg-sprite',
    name: 'SVG Sprite Sheet',
    description: 'Bundle icons and illustrations into an optimized SVG sprite sheet.',
    category: 'code-gen',
    icon: 'Layers',
    isInstalled: false,
    tags: ['svg', 'sprite', 'icons', 'bundle', 'optimize'],
    version: '1.0.0',
    author: 'DevKit',
  },
  {
    id: 'code-gen-markdown',
    name: 'Markdown Export',
    description: 'Export design specs and annotations as formatted Markdown documentation.',
    category: 'code-gen',
    icon: 'Hash',
    isInstalled: false,
    tags: ['markdown', 'documentation', 'specs', 'annotations', 'export'],
    version: '1.1.0',
    author: 'DevKit',
  },

  // ── Handoff (7) ────────────────────────────────────────────
  {
    id: 'handoff-specs',
    name: 'Design Specs',
    description: 'Generate detailed design specs with measurements, colors, and fonts.',
    category: 'handoff',
    icon: 'Ruler',
    isInstalled: false,
    isPopular: true,
    tags: ['specs', 'measurements', 'colors', 'fonts', 'documentation'],
    version: '2.0.0',
    author: 'HandoffKit',
  },
  {
    id: 'handoff-inspect',
    name: 'Inspect Tool',
    description: 'Click any element to view its CSS properties, spacing, and dimensions.',
    category: 'handoff',
    icon: 'Search',
    isInstalled: false,
    isPopular: true,
    tags: ['inspect', 'css', 'properties', 'spacing', 'dimensions'],
    version: '1.5.0',
    author: 'HandoffKit',
  },
  {
    id: 'handoff-asset-export',
    name: 'Asset Export Panel',
    description: 'Bulk export all design assets with proper naming conventions and formats.',
    category: 'handoff',
    icon: 'Download',
    isInstalled: false,
    tags: ['asset', 'export', 'bulk', 'naming', 'format'],
    version: '1.3.0',
    author: 'HandoffKit',
  },
  {
    id: 'handoff-zeplin-style',
    name: 'Zeplin-Style Export',
    description: 'Export a Zeplin-compatible spec sheet with redline annotations.',
    category: 'handoff',
    icon: 'ExternalLink',
    isInstalled: false,
    tags: ['zeplin', 'redline', 'annotation', 'spec-sheet', 'developer'],
    version: '1.1.0',
    author: 'HandoffKit',
  },
  {
    id: 'handoff-css-snippets',
    name: 'CSS Snippets',
    description: 'Copy CSS snippets for any element including gradients and shadows.',
    category: 'handoff',
    icon: 'Clipboard',
    isInstalled: false,
    isPopular: true,
    tags: ['css', 'snippet', 'copy', 'gradient', 'shadow'],
    version: '1.4.0',
    author: 'HandoffKit',
  },
  {
    id: 'handoff-measure',
    name: 'Measure Tool',
    description: 'Measure distances between elements with pixel-precise readouts.',
    category: 'handoff',
    icon: 'Ruler',
    isInstalled: false,
    tags: ['measure', 'distance', 'pixel', 'precise', 'spacing'],
    version: '1.2.0',
    author: 'HandoffKit',
  },
  {
    id: 'handoff-developer-mode',
    name: 'Developer Mode',
    description: 'Toggle a developer overlay showing code hints and pixel coordinates.',
    category: 'handoff',
    icon: 'Code',
    isInstalled: false,
    isPopular: true,
    tags: ['developer', 'overlay', 'code-hints', 'coordinates', 'inspect'],
    version: '1.0.0',
    author: 'HandoffKit',
  },
]
